/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "douyin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(douyin_Response, douyin_Response, 2)


PB_BIND(douyin_Response_RouteParamsEntry, douyin_Response_RouteParamsEntry, AUTO)


PB_BIND(douyin_Message, douyin_Message, 2)


PB_BIND(douyin_ChatMessage, douyin_ChatMessage, 4)


PB_BIND(douyin_LandscapeAreaCommon, douyin_LandscapeAreaCommon, AUTO)


PB_BIND(douyin_RoomUserSeqMessage, douyin_RoomUserSeqMessage, 4)


PB_BIND(douyin_CommonTextMessage, douyin_CommonTextMessage, 4)


PB_BIND(douyin_UpdateFanTicketMessage, douyin_UpdateFanTicketMessage, 4)


PB_BIND(douyin_RoomUserSeqMessageContributor, douyin_RoomUserSeqMessageContributor, 4)


PB_BIND(douyin_GiftMessage, douyin_GiftMessage, 4)


PB_BIND(douyin_GiftStruct, douyin_GiftStruct, 2)


PB_BIND(douyin_GiftIMPriority, douyin_GiftIMPriority, AUTO)


PB_BIND(douyin_TextEffect, douyin_TextEffect, 2)


PB_BIND(douyin_TextEffectDetail, douyin_TextEffectDetail, 2)


PB_BIND(douyin_MemberMessage, douyin_MemberMessage, 4)


PB_BIND(douyin_PublicAreaCommon, douyin_PublicAreaCommon, 2)


PB_BIND(douyin_EffectConfig, douyin_EffectConfig, 2)


PB_BIND(douyin_EffectConfig_ExtraMapEntry, douyin_EffectConfig_ExtraMapEntry, AUTO)


PB_BIND(douyin_Text, douyin_Text, 2)


PB_BIND(douyin_TextPiece, douyin_TextPiece, 4)


PB_BIND(douyin_TextPieceImage, douyin_TextPieceImage, 2)


PB_BIND(douyin_TextPiecePatternRef, douyin_TextPiecePatternRef, 2)


PB_BIND(douyin_TextPieceHeart, douyin_TextPieceHeart, 2)


PB_BIND(douyin_TextPieceGift, douyin_TextPieceGift, 2)


PB_BIND(douyin_PatternRef, douyin_PatternRef, 2)


PB_BIND(douyin_TextPieceUser, douyin_TextPieceUser, 4)


PB_BIND(douyin_TextFormat, douyin_TextFormat, 2)


PB_BIND(douyin_LikeMessage, douyin_LikeMessage, 4)


PB_BIND(douyin_SocialMessage, douyin_SocialMessage, 4)


PB_BIND(douyin_PicoDisplayInfo, douyin_PicoDisplayInfo, 2)


PB_BIND(douyin_DoubleLikeDetail, douyin_DoubleLikeDetail, AUTO)


PB_BIND(douyin_DisplayControlInfo, douyin_DisplayControlInfo, AUTO)


PB_BIND(douyin_EpisodeChatMessage, douyin_EpisodeChatMessage, 4)


PB_BIND(douyin_MatchAgainstScoreMessage, douyin_MatchAgainstScoreMessage, 4)


PB_BIND(douyin_Against, douyin_Against, 2)


PB_BIND(douyin_Common, douyin_Common, 4)


PB_BIND(douyin_User, douyin_User, 4)


PB_BIND(douyin_FollowInfo, douyin_FollowInfo, 2)


PB_BIND(douyin_Image, douyin_Image, 2)


PB_BIND(douyin_NinePatchSetting, douyin_NinePatchSetting, AUTO)


PB_BIND(douyin_ImageContent, douyin_ImageContent, 2)


PB_BIND(douyin_RoomStatsMessage, douyin_RoomStatsMessage, 4)


PB_BIND(douyin_BackupSEIMessage, douyin_BackupSEIMessage, 4)


PB_BIND(douyin_RoomRankMessage, douyin_RoomRankMessage, 4)


PB_BIND(douyin_RoomRank, douyin_RoomRank, 4)


PB_BIND(douyin_PushFrame, douyin_PushFrame, 2)


PB_BIND(douyin_kk, douyin_kk, AUTO)


PB_BIND(douyin_SendMessageBody, douyin_SendMessageBody, 2)


PB_BIND(douyin_ExtList, douyin_ExtList, 2)


PB_BIND(douyin_Rsp, douyin_Rsp, 2)


PB_BIND(douyin_Rsp_F, douyin_Rsp_F, 2)


PB_BIND(douyin_PreMessage, douyin_PreMessage, 2)


PB_BIND(douyin_HeadersList, douyin_HeadersList, 2)





