/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DOUYIN_DOUYIN_PB_H_INCLUDED
#define PB_DOUYIN_DOUYIN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _douyin_CommentTypeTag {
    douyin_CommentTypeTag_COMMENTTYPETAGUNKNOWN = 0,
    douyin_CommentTypeTag_COMMENTTYPETAGSTAR = 1
} douyin_CommentTypeTag;

/* Struct definitions */
typedef struct _douyin_Response {
    pb_callback_t messagesList;
    char cursor[128];
    uint64_t fetchInterval;
    uint64_t now;
    char internalExt[128];
    uint32_t fetchType;
    pb_callback_t routeParams;
    uint64_t heartbeatDuration;
    bool needAck;
    char pushServer[128];
    char liveCursor[128];
    bool historyNoMore;
} douyin_Response;

typedef struct _douyin_Response_RouteParamsEntry {
    pb_callback_t key;
    pb_callback_t value;
} douyin_Response_RouteParamsEntry;

typedef struct _douyin_Message {
    char method[128];
    pb_callback_t payload;
    int64_t msgId;
    int32_t msgType;
    int64_t offset;
    bool needWrdsStore;
    int64_t wrdsVersion;
    char wrdsSubKey[128];
} douyin_Message;

typedef struct _douyin_LandscapeAreaCommon {
    bool showHead;
    bool showNickname;
    bool showFontColor;
    pb_callback_t colorValueList;
    pb_callback_t commentTypeTagsList;
} douyin_LandscapeAreaCommon;

typedef struct _douyin_GiftIMPriority {
    pb_callback_t queueSizesList;
    uint64_t selfQueuePriority;
    uint64_t priority;
} douyin_GiftIMPriority;

typedef struct _douyin_EffectConfig_ExtraMapEntry {
    pb_callback_t key;
    pb_callback_t value;
} douyin_EffectConfig_ExtraMapEntry;

typedef struct _douyin_TextPiecePatternRef {
    char key[128];
    char defaultPattern[128];
} douyin_TextPiecePatternRef;

typedef struct _douyin_TextPieceHeart {
    char color[128];
} douyin_TextPieceHeart;

typedef struct _douyin_PatternRef {
    char key[128];
    char defaultPattern[128];
} douyin_PatternRef;

typedef struct _douyin_TextPieceGift {
    uint64_t giftId;
    bool has_nameRef;
    douyin_PatternRef nameRef;
} douyin_TextPieceGift;

typedef struct _douyin_TextFormat {
    char color[128];
    bool bold;
    bool italic;
    uint32_t weight;
    uint32_t italicAngle;
    uint32_t fontSize;
    bool useHeighLightColor;
    bool useRemoteClor;
} douyin_TextFormat;

typedef struct _douyin_Text {
    char key[128];
    char defaultPatter[128];
    bool has_defaultFormat;
    douyin_TextFormat defaultFormat;
    pb_callback_t piecesList;
} douyin_Text;

typedef struct _douyin_DoubleLikeDetail {
    bool doubleFlag;
    uint32_t seqId;
    uint32_t renewalsNum;
    uint32_t triggersNum;
} douyin_DoubleLikeDetail;

typedef struct _douyin_DisplayControlInfo {
    bool showText;
    bool showIcons;
} douyin_DisplayControlInfo;

typedef struct _douyin_FollowInfo {
    uint64_t followingCount;
    uint64_t followerCount;
    uint64_t followStatus;
    uint64_t pushStatus;
    char remarkName[128];
    char followerCountStr[128];
    char followingCountStr[128];
} douyin_FollowInfo;

typedef struct _douyin_NinePatchSetting {
    pb_callback_t settingListList;
} douyin_NinePatchSetting;

typedef struct _douyin_ImageContent {
    char name[128];
    char fontColor[128];
    uint64_t level;
    char alternativeText[128];
} douyin_ImageContent;

typedef struct _douyin_Image {
    pb_callback_t urlListList;
    char uri[128];
    uint64_t height;
    uint64_t width;
    char avgColor[128];
    uint32_t imageType;
    char openWebUrl[128];
    bool has_content;
    douyin_ImageContent content;
    bool isAnimated;
    bool has_FlexSettingList;
    douyin_NinePatchSetting FlexSettingList;
    bool has_TextSettingList;
    douyin_NinePatchSetting TextSettingList;
} douyin_Image;

typedef struct _douyin_GiftStruct {
    bool has_image;
    douyin_Image image;
    char describe[128];
    bool notify;
    uint64_t duration;
    uint64_t id;
    bool forLinkmic;
    bool doodle;
    bool forFansclub;
    bool combo;
    uint32_t type;
    uint32_t diamondCount;
    bool isDisplayedOnPanel;
    uint64_t primaryEffectId;
    bool has_giftLabelIcon;
    douyin_Image giftLabelIcon;
    char name[128];
    char region[128];
    char manual[128];
    bool forCustom;
    bool has_icon;
    douyin_Image icon;
    uint32_t actionType;
} douyin_GiftStruct;

typedef struct _douyin_TextEffectDetail {
    bool has_text;
    douyin_Text text;
    uint32_t textFontSize;
    bool has_background;
    douyin_Image background;
    uint32_t start;
    uint32_t duration;
    uint32_t x;
    uint32_t y;
    uint32_t width;
    uint32_t height;
    uint32_t shadowDx;
    uint32_t shadowDy;
    uint32_t shadowRadius;
    char shadowColor[128];
    char strokeColor[128];
    uint32_t strokeWidth;
} douyin_TextEffectDetail;

typedef struct _douyin_TextEffect {
    bool has_portrait;
    douyin_TextEffectDetail portrait;
    bool has_landscape;
    douyin_TextEffectDetail landscape;
} douyin_TextEffect;

typedef struct _douyin_PublicAreaCommon {
    bool has_userLabel;
    douyin_Image userLabel;
    uint64_t userConsumeInRoom;
    uint64_t userSendGiftCntInRoom;
} douyin_PublicAreaCommon;

typedef struct _douyin_EffectConfig {
    uint64_t type;
    bool has_icon;
    douyin_Image icon;
    uint64_t avatarPos;
    bool has_text;
    douyin_Text text;
    bool has_textIcon;
    douyin_Image textIcon;
    uint32_t stayTime;
    uint64_t animAssetId;
    bool has_badge;
    douyin_Image badge;
    pb_callback_t flexSettingArrayList;
    bool has_textIconOverlay;
    douyin_Image textIconOverlay;
    bool has_animatedBadge;
    douyin_Image animatedBadge;
    bool hasSweepLight;
    pb_callback_t textFlexSettingArrayList;
    uint64_t centerAnimAssetId;
    bool has_dynamicImage;
    douyin_Image dynamicImage;
    pb_callback_t extraMap;
    uint64_t mp4AnimAssetId;
    uint64_t priority;
    uint64_t maxWaitTime;
    char dressId[128];
    uint64_t alignment;
    uint64_t alignmentOffset;
} douyin_EffectConfig;

typedef struct _douyin_TextPieceImage {
    bool has_image;
    douyin_Image image;
    float scalingRate;
} douyin_TextPieceImage;

typedef struct _douyin_PicoDisplayInfo {
    uint64_t comboSumCount;
    char emoji[128];
    bool has_emojiIcon;
    douyin_Image emojiIcon;
    char emojiText[128];
} douyin_PicoDisplayInfo;

typedef struct _douyin_Against {
    char leftName[128];
    bool has_leftLogo;
    douyin_Image leftLogo;
    char leftGoal[128];
    char rightName[128];
    bool has_rightLogo;
    douyin_Image rightLogo;
    char rightGoal[128];
    uint64_t timestamp;
    uint64_t version;
    uint64_t leftTeamId;
    uint64_t rightTeamId;
    uint64_t diffSei2absSecond;
    uint32_t finalGoalStage;
    uint32_t currentGoalStage;
    uint32_t leftScoreAddition;
    uint32_t rightScoreAddition;
    uint64_t leftGoalInt;
    uint64_t rightGoalInt;
} douyin_Against;

typedef struct _douyin_User {
    uint64_t id;
    uint64_t shortId;
    char nickName[128];
    uint32_t gender;
    char Signature[128];
    uint32_t Level;
    uint64_t Birthday;
    char Telephone[128];
    bool has_AvatarThumb;
    douyin_Image AvatarThumb;
    bool has_AvatarMedium;
    douyin_Image AvatarMedium;
    bool has_AvatarLarge;
    douyin_Image AvatarLarge;
    bool Verified;
    uint32_t Experience;
    char city[128];
    int32_t Status;
    uint64_t CreateTime;
    uint64_t ModifyTime;
    uint32_t Secret;
    char ShareQrcodeUri[128];
    uint32_t IncomeSharePercent;
    pb_callback_t BadgeImageList;
    bool has_FollowInfo;
    douyin_FollowInfo FollowInfo;
    char SpecialId[128];
    bool has_AvatarBorder;
    douyin_Image AvatarBorder;
    bool has_Medal;
    douyin_Image Medal;
    pb_callback_t RealTimeIconsList;
    char displayId[128];
    char secUid[128];
    uint64_t fanTicketCount;
    char idStr[128];
    uint32_t ageRange;
} douyin_User;

typedef struct _douyin_RoomUserSeqMessageContributor {
    uint64_t score;
    bool has_user;
    douyin_User user;
    uint64_t rank;
    uint64_t delta;
    bool isHidden;
    char scoreDescription[128];
    char exactlyScore[128];
} douyin_RoomUserSeqMessageContributor;

typedef struct _douyin_TextPieceUser {
    bool has_user;
    douyin_User user;
    bool withColon;
} douyin_TextPieceUser;

typedef struct _douyin_TextPiece {
    bool type;
    bool has_format;
    douyin_TextFormat format;
    char stringValue[128];
    bool has_userValue;
    douyin_TextPieceUser userValue;
    bool has_giftValue;
    douyin_TextPieceGift giftValue;
    bool has_heartValue;
    douyin_TextPieceHeart heartValue;
    bool has_patternRefValue;
    douyin_TextPiecePatternRef patternRefValue;
    bool has_imageValue;
    douyin_TextPieceImage imageValue;
} douyin_TextPiece;

typedef struct _douyin_EpisodeChatMessage {
    bool has_common;
    douyin_Message common;
    bool has_user;
    douyin_User user;
    char content[128];
    bool visibleToSende;
    bool has_giftImage;
    douyin_Image giftImage;
    uint64_t agreeMsgId;
    pb_callback_t colorValueList;
} douyin_EpisodeChatMessage;

typedef struct _douyin_Common {
    char method[128];
    uint64_t msgId;
    uint64_t roomId;
    uint64_t createTime;
    uint32_t monitor;
    bool isShowMsg;
    char describe[128];
    uint64_t foldType;
    uint64_t anchorFoldType;
    uint64_t priorityScore;
    char logId[128];
    char msgProcessFilterK[128];
    char msgProcessFilterV[128];
    bool has_user;
    douyin_User user;
    uint64_t anchorFoldTypeV2;
    uint64_t processAtSeiTimeMs;
    uint64_t randomDispatchMs;
    bool isDispatch;
    uint64_t channelId;
    uint64_t diffSei2absSecond;
    uint64_t anchorFoldDuration;
} douyin_Common;

typedef struct _douyin_ChatMessage {
    bool has_common;
    douyin_Common common;
    bool has_user;
    douyin_User user;
    char content[128];
    bool visibleToSender;
    bool has_backgroundImage;
    douyin_Image backgroundImage;
    char fullScreenTextColor[128];
    bool has_backgroundImageV2;
    douyin_Image backgroundImageV2;
    bool has_publicAreaCommon;
    douyin_PublicAreaCommon publicAreaCommon;
    bool has_giftImage;
    douyin_Image giftImage;
    uint64_t agreeMsgId;
    uint32_t priorityLevel;
    bool has_landscapeAreaCommon;
    douyin_LandscapeAreaCommon landscapeAreaCommon;
    uint64_t eventTime;
    bool sendReview;
    bool fromIntercom;
    bool intercomHideUserCard;
    char chatBy[128];
    uint32_t individualChatPriority;
    bool has_rtfContent;
    douyin_Text rtfContent;
} douyin_ChatMessage;

typedef struct _douyin_RoomUserSeqMessage {
    bool has_common;
    douyin_Common common;
    pb_callback_t ranksList;
    int64_t total;
    char popStr[128];
    pb_callback_t seatsList;
    int64_t popularity;
    int64_t totalUser;
    char totalUserStr[128];
    char totalStr[128];
    char onlineUserForAnchor[128];
    char totalPvForAnchor[128];
    char upRightStatsStr[128];
    char upRightStatsStrComplete[128];
} douyin_RoomUserSeqMessage;

typedef struct _douyin_CommonTextMessage {
    bool has_common;
    douyin_Common common;
    bool has_user;
    douyin_User user;
    char scene[128];
} douyin_CommonTextMessage;

typedef struct _douyin_UpdateFanTicketMessage {
    bool has_common;
    douyin_Common common;
    char roomFanTicketCountText[128];
    uint64_t roomFanTicketCount;
    bool forceUpdate;
} douyin_UpdateFanTicketMessage;

typedef struct _douyin_GiftMessage {
    bool has_common;
    douyin_Common common;
    uint64_t giftId;
    uint64_t fanTicketCount;
    uint64_t groupCount;
    uint64_t repeatCount;
    uint64_t comboCount;
    bool has_user;
    douyin_User user;
    bool has_toUser;
    douyin_User toUser;
    uint32_t repeatEnd;
    bool has_textEffect;
    douyin_TextEffect textEffect;
    uint64_t groupId;
    uint64_t incomeTaskgifts;
    uint64_t roomFanTicketCount;
    bool has_priority;
    douyin_GiftIMPriority priority;
    bool has_gift;
    douyin_GiftStruct gift;
    char logId[128];
    uint64_t sendType;
    bool has_publicAreaCommon;
    douyin_PublicAreaCommon publicAreaCommon;
    bool has_trayDisplayText;
    douyin_Text trayDisplayText;
    uint64_t bannedDisplayEffects;
    bool displayForSelf;
    char interactGiftInfo[128];
    char diyItemInfo[128];
    pb_callback_t minAssetSetList;
    uint64_t totalCount;
    uint32_t clientGiftSource;
    pb_callback_t toUserIdsList;
    uint64_t sendTime;
    uint64_t forceDisplayEffects;
    char traceId[128];
    uint64_t effectDisplayTs;
} douyin_GiftMessage;

typedef struct _douyin_MemberMessage {
    bool has_common;
    douyin_Common common;
    bool has_user;
    douyin_User user;
    uint64_t memberCount;
    bool has_operator_;
    douyin_User operator_;
    bool isSetToAdmin;
    bool isTopUser;
    uint64_t rankScore;
    uint64_t topUserNo;
    uint64_t enterType;
    uint64_t action;
    char actionDescription[128];
    uint64_t userId;
    bool has_effectConfig;
    douyin_EffectConfig effectConfig;
    char popStr[128];
    bool has_enterEffectConfig;
    douyin_EffectConfig enterEffectConfig;
    bool has_backgroundImage;
    douyin_Image backgroundImage;
    bool has_backgroundImageV2;
    douyin_Image backgroundImageV2;
    bool has_anchorDisplayText;
    douyin_Text anchorDisplayText;
    bool has_publicAreaCommon;
    douyin_PublicAreaCommon publicAreaCommon;
    uint64_t userEnterTipType;
    uint64_t anchorEnterTipType;
} douyin_MemberMessage;

typedef struct _douyin_LikeMessage {
    bool has_common;
    douyin_Common common;
    uint64_t count;
    uint64_t total;
    uint64_t color;
    bool has_user;
    douyin_User user;
    char icon[128];
    bool has_doubleLikeDetail;
    douyin_DoubleLikeDetail doubleLikeDetail;
    bool has_displayControlInfo;
    douyin_DisplayControlInfo displayControlInfo;
    uint64_t linkmicGuestUid;
    char scene[128];
    bool has_picoDisplayInfo;
    douyin_PicoDisplayInfo picoDisplayInfo;
} douyin_LikeMessage;

typedef struct _douyin_SocialMessage {
    bool has_common;
    douyin_Common common;
    bool has_user;
    douyin_User user;
    uint64_t shareType;
    uint64_t action;
    char shareTarget[128];
    uint64_t followCount;
    bool has_publicAreaCommon;
    douyin_PublicAreaCommon publicAreaCommon;
} douyin_SocialMessage;

typedef struct _douyin_MatchAgainstScoreMessage {
    bool has_common;
    douyin_Common common;
    bool has_against;
    douyin_Against against;
    uint32_t matchStatus;
    uint32_t displayStatus;
} douyin_MatchAgainstScoreMessage;

typedef struct _douyin_PushFrame {
    uint64_t seqId;
    uint64_t logId;
    uint64_t service;
    uint64_t method;
    pb_callback_t headersList;
    char payloadEncoding[128];
    char payloadType[128];
    pb_callback_t payload;
} douyin_PushFrame;

typedef struct _douyin_kk {
    uint32_t k;
} douyin_kk;

typedef struct _douyin_SendMessageBody {
    char conversationId[128];
    uint32_t conversationType;
    uint64_t conversationShortId;
    char content[128];
    pb_callback_t ext;
    uint32_t messageType;
    char ticket[128];
    char clientMessageId[128];
} douyin_SendMessageBody;

typedef struct _douyin_ExtList {
    char key[128];
    char value[128];
} douyin_ExtList;

typedef struct _douyin_Rsp_F {
    uint64_t q1;
    uint64_t q3;
    char q4[128];
    uint64_t q5;
} douyin_Rsp_F;

typedef struct _douyin_Rsp {
    int32_t a;
    int32_t b;
    int32_t c;
    char d[128];
    int32_t e;
    bool has_f;
    douyin_Rsp_F f;
    char g[128];
    uint64_t h;
    uint64_t i;
    uint64_t j;
} douyin_Rsp;

typedef struct _douyin_PreMessage {
    uint32_t cmd;
    uint32_t sequenceId;
    char sdkVersion[128];
    char token[128];
    uint32_t refer;
    uint32_t inboxType;
    char buildNumber[128];
    bool has_sendMessageBody;
    douyin_SendMessageBody sendMessageBody;
    char aa[128];
    char devicePlatform[128];
    pb_callback_t headers;
    uint32_t authType;
    char biz[128];
    char access[128];
} douyin_PreMessage;

typedef struct _douyin_HeadersList {
    char key[128];
    char value[128];
} douyin_HeadersList;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _douyin_CommentTypeTag_MIN douyin_CommentTypeTag_COMMENTTYPETAGUNKNOWN
#define _douyin_CommentTypeTag_MAX douyin_CommentTypeTag_COMMENTTYPETAGSTAR
#define _douyin_CommentTypeTag_ARRAYSIZE ((douyin_CommentTypeTag)(douyin_CommentTypeTag_COMMENTTYPETAGSTAR+1))





#define douyin_LandscapeAreaCommon_commentTypeTagsList_ENUMTYPE douyin_CommentTypeTag














































/* Initializer values for message structs */
#define douyin_Response_init_default             {{{NULL}, NULL}, "", 0, 0, "", 0, {{NULL}, NULL}, 0, 0, "", "", 0}
#define douyin_Response_RouteParamsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define douyin_Message_init_default              {"", {{NULL}, NULL}, 0, 0, 0, 0, 0, ""}
#define douyin_ChatMessage_init_default          {false, douyin_Common_init_default, false, douyin_User_init_default, "", 0, false, douyin_Image_init_default, "", false, douyin_Image_init_default, false, douyin_PublicAreaCommon_init_default, false, douyin_Image_init_default, 0, 0, false, douyin_LandscapeAreaCommon_init_default, 0, 0, 0, 0, "", 0, false, douyin_Text_init_default}
#define douyin_LandscapeAreaCommon_init_default  {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define douyin_RoomUserSeqMessage_init_default   {false, douyin_Common_init_default, {{NULL}, NULL}, 0, "", {{NULL}, NULL}, 0, 0, "", "", "", "", "", ""}
#define douyin_CommonTextMessage_init_default    {false, douyin_Common_init_default, false, douyin_User_init_default, ""}
#define douyin_UpdateFanTicketMessage_init_default {false, douyin_Common_init_default, "", 0, 0}
#define douyin_RoomUserSeqMessageContributor_init_default {0, false, douyin_User_init_default, 0, 0, 0, "", ""}
#define douyin_GiftMessage_init_default          {false, douyin_Common_init_default, 0, 0, 0, 0, 0, false, douyin_User_init_default, false, douyin_User_init_default, 0, false, douyin_TextEffect_init_default, 0, 0, 0, false, douyin_GiftIMPriority_init_default, false, douyin_GiftStruct_init_default, "", 0, false, douyin_PublicAreaCommon_init_default, false, douyin_Text_init_default, 0, 0, "", "", {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, 0, "", 0}
#define douyin_GiftStruct_init_default           {false, douyin_Image_init_default, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, douyin_Image_init_default, "", "", "", 0, false, douyin_Image_init_default, 0}
#define douyin_GiftIMPriority_init_default       {{{NULL}, NULL}, 0, 0}
#define douyin_TextEffect_init_default           {false, douyin_TextEffectDetail_init_default, false, douyin_TextEffectDetail_init_default}
#define douyin_TextEffectDetail_init_default     {false, douyin_Text_init_default, 0, false, douyin_Image_init_default, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0}
#define douyin_MemberMessage_init_default        {false, douyin_Common_init_default, false, douyin_User_init_default, 0, false, douyin_User_init_default, 0, 0, 0, 0, 0, 0, "", 0, false, douyin_EffectConfig_init_default, "", false, douyin_EffectConfig_init_default, false, douyin_Image_init_default, false, douyin_Image_init_default, false, douyin_Text_init_default, false, douyin_PublicAreaCommon_init_default, 0, 0}
#define douyin_PublicAreaCommon_init_default     {false, douyin_Image_init_default, 0, 0}
#define douyin_EffectConfig_init_default         {0, false, douyin_Image_init_default, 0, false, douyin_Text_init_default, false, douyin_Image_init_default, 0, 0, false, douyin_Image_init_default, {{NULL}, NULL}, false, douyin_Image_init_default, false, douyin_Image_init_default, 0, {{NULL}, NULL}, 0, false, douyin_Image_init_default, {{NULL}, NULL}, 0, 0, 0, "", 0, 0}
#define douyin_EffectConfig_ExtraMapEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define douyin_Text_init_default                 {"", "", false, douyin_TextFormat_init_default, {{NULL}, NULL}}
#define douyin_TextPiece_init_default            {0, false, douyin_TextFormat_init_default, "", false, douyin_TextPieceUser_init_default, false, douyin_TextPieceGift_init_default, false, douyin_TextPieceHeart_init_default, false, douyin_TextPiecePatternRef_init_default, false, douyin_TextPieceImage_init_default}
#define douyin_TextPieceImage_init_default       {false, douyin_Image_init_default, 0}
#define douyin_TextPiecePatternRef_init_default  {"", ""}
#define douyin_TextPieceHeart_init_default       {""}
#define douyin_TextPieceGift_init_default        {0, false, douyin_PatternRef_init_default}
#define douyin_PatternRef_init_default           {"", ""}
#define douyin_TextPieceUser_init_default        {false, douyin_User_init_default, 0}
#define douyin_TextFormat_init_default           {"", 0, 0, 0, 0, 0, 0, 0}
#define douyin_LikeMessage_init_default          {false, douyin_Common_init_default, 0, 0, 0, false, douyin_User_init_default, "", false, douyin_DoubleLikeDetail_init_default, false, douyin_DisplayControlInfo_init_default, 0, "", false, douyin_PicoDisplayInfo_init_default}
#define douyin_SocialMessage_init_default        {false, douyin_Common_init_default, false, douyin_User_init_default, 0, 0, "", 0, false, douyin_PublicAreaCommon_init_default}
#define douyin_PicoDisplayInfo_init_default      {0, "", false, douyin_Image_init_default, ""}
#define douyin_DoubleLikeDetail_init_default     {0, 0, 0, 0}
#define douyin_DisplayControlInfo_init_default   {0, 0}
#define douyin_EpisodeChatMessage_init_default   {false, douyin_Message_init_default, false, douyin_User_init_default, "", 0, false, douyin_Image_init_default, 0, {{NULL}, NULL}}
#define douyin_MatchAgainstScoreMessage_init_default {false, douyin_Common_init_default, false, douyin_Against_init_default, 0, 0}
#define douyin_Against_init_default              {"", false, douyin_Image_init_default, "", "", false, douyin_Image_init_default, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define douyin_Common_init_default               {"", 0, 0, 0, 0, 0, "", 0, 0, 0, "", "", "", false, douyin_User_init_default, 0, 0, 0, 0, 0, 0, 0}
#define douyin_User_init_default                 {0, 0, "", 0, "", 0, 0, "", false, douyin_Image_init_default, false, douyin_Image_init_default, false, douyin_Image_init_default, 0, 0, "", 0, 0, 0, 0, "", 0, {{NULL}, NULL}, false, douyin_FollowInfo_init_default, "", false, douyin_Image_init_default, false, douyin_Image_init_default, {{NULL}, NULL}, "", "", 0, "", 0}
#define douyin_FollowInfo_init_default           {0, 0, 0, 0, "", "", ""}
#define douyin_Image_init_default                {{{NULL}, NULL}, "", 0, 0, "", 0, "", false, douyin_ImageContent_init_default, 0, false, douyin_NinePatchSetting_init_default, false, douyin_NinePatchSetting_init_default}
#define douyin_NinePatchSetting_init_default     {{{NULL}, NULL}}
#define douyin_ImageContent_init_default         {"", "", 0, ""}
#define douyin_PushFrame_init_default            {0, 0, 0, 0, {{NULL}, NULL}, "", "", {{NULL}, NULL}}
#define douyin_kk_init_default                   {0}
#define douyin_SendMessageBody_init_default      {"", 0, 0, "", {{NULL}, NULL}, 0, "", ""}
#define douyin_ExtList_init_default              {"", ""}
#define douyin_Rsp_init_default                  {0, 0, 0, "", 0, false, douyin_Rsp_F_init_default, "", 0, 0, 0}
#define douyin_Rsp_F_init_default                {0, 0, "", 0}
#define douyin_PreMessage_init_default           {0, 0, "", "", 0, 0, "", false, douyin_SendMessageBody_init_default, "", "", {{NULL}, NULL}, 0, "", ""}
#define douyin_HeadersList_init_default          {"", ""}
#define douyin_Response_init_zero                {{{NULL}, NULL}, "", 0, 0, "", 0, {{NULL}, NULL}, 0, 0, "", "", 0}
#define douyin_Response_RouteParamsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define douyin_Message_init_zero                 {"", {{NULL}, NULL}, 0, 0, 0, 0, 0, ""}
#define douyin_ChatMessage_init_zero             {false, douyin_Common_init_zero, false, douyin_User_init_zero, "", 0, false, douyin_Image_init_zero, "", false, douyin_Image_init_zero, false, douyin_PublicAreaCommon_init_zero, false, douyin_Image_init_zero, 0, 0, false, douyin_LandscapeAreaCommon_init_zero, 0, 0, 0, 0, "", 0, false, douyin_Text_init_zero}
#define douyin_LandscapeAreaCommon_init_zero     {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define douyin_RoomUserSeqMessage_init_zero      {false, douyin_Common_init_zero, {{NULL}, NULL}, 0, "", {{NULL}, NULL}, 0, 0, "", "", "", "", "", ""}
#define douyin_CommonTextMessage_init_zero       {false, douyin_Common_init_zero, false, douyin_User_init_zero, ""}
#define douyin_UpdateFanTicketMessage_init_zero  {false, douyin_Common_init_zero, "", 0, 0}
#define douyin_RoomUserSeqMessageContributor_init_zero {0, false, douyin_User_init_zero, 0, 0, 0, "", ""}
#define douyin_GiftMessage_init_zero             {false, douyin_Common_init_zero, 0, 0, 0, 0, 0, false, douyin_User_init_zero, false, douyin_User_init_zero, 0, false, douyin_TextEffect_init_zero, 0, 0, 0, false, douyin_GiftIMPriority_init_zero, false, douyin_GiftStruct_init_zero, "", 0, false, douyin_PublicAreaCommon_init_zero, false, douyin_Text_init_zero, 0, 0, "", "", {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, 0, "", 0}
#define douyin_GiftStruct_init_zero              {false, douyin_Image_init_zero, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, douyin_Image_init_zero, "", "", "", 0, false, douyin_Image_init_zero, 0}
#define douyin_GiftIMPriority_init_zero          {{{NULL}, NULL}, 0, 0}
#define douyin_TextEffect_init_zero              {false, douyin_TextEffectDetail_init_zero, false, douyin_TextEffectDetail_init_zero}
#define douyin_TextEffectDetail_init_zero        {false, douyin_Text_init_zero, 0, false, douyin_Image_init_zero, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0}
#define douyin_MemberMessage_init_zero           {false, douyin_Common_init_zero, false, douyin_User_init_zero, 0, false, douyin_User_init_zero, 0, 0, 0, 0, 0, 0, "", 0, false, douyin_EffectConfig_init_zero, "", false, douyin_EffectConfig_init_zero, false, douyin_Image_init_zero, false, douyin_Image_init_zero, false, douyin_Text_init_zero, false, douyin_PublicAreaCommon_init_zero, 0, 0}
#define douyin_PublicAreaCommon_init_zero        {false, douyin_Image_init_zero, 0, 0}
#define douyin_EffectConfig_init_zero            {0, false, douyin_Image_init_zero, 0, false, douyin_Text_init_zero, false, douyin_Image_init_zero, 0, 0, false, douyin_Image_init_zero, {{NULL}, NULL}, false, douyin_Image_init_zero, false, douyin_Image_init_zero, 0, {{NULL}, NULL}, 0, false, douyin_Image_init_zero, {{NULL}, NULL}, 0, 0, 0, "", 0, 0}
#define douyin_EffectConfig_ExtraMapEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define douyin_Text_init_zero                    {"", "", false, douyin_TextFormat_init_zero, {{NULL}, NULL}}
#define douyin_TextPiece_init_zero               {0, false, douyin_TextFormat_init_zero, "", false, douyin_TextPieceUser_init_zero, false, douyin_TextPieceGift_init_zero, false, douyin_TextPieceHeart_init_zero, false, douyin_TextPiecePatternRef_init_zero, false, douyin_TextPieceImage_init_zero}
#define douyin_TextPieceImage_init_zero          {false, douyin_Image_init_zero, 0}
#define douyin_TextPiecePatternRef_init_zero     {"", ""}
#define douyin_TextPieceHeart_init_zero          {""}
#define douyin_TextPieceGift_init_zero           {0, false, douyin_PatternRef_init_zero}
#define douyin_PatternRef_init_zero              {"", ""}
#define douyin_TextPieceUser_init_zero           {false, douyin_User_init_zero, 0}
#define douyin_TextFormat_init_zero              {"", 0, 0, 0, 0, 0, 0, 0}
#define douyin_LikeMessage_init_zero             {false, douyin_Common_init_zero, 0, 0, 0, false, douyin_User_init_zero, "", false, douyin_DoubleLikeDetail_init_zero, false, douyin_DisplayControlInfo_init_zero, 0, "", false, douyin_PicoDisplayInfo_init_zero}
#define douyin_SocialMessage_init_zero           {false, douyin_Common_init_zero, false, douyin_User_init_zero, 0, 0, "", 0, false, douyin_PublicAreaCommon_init_zero}
#define douyin_PicoDisplayInfo_init_zero         {0, "", false, douyin_Image_init_zero, ""}
#define douyin_DoubleLikeDetail_init_zero        {0, 0, 0, 0}
#define douyin_DisplayControlInfo_init_zero      {0, 0}
#define douyin_EpisodeChatMessage_init_zero      {false, douyin_Message_init_zero, false, douyin_User_init_zero, "", 0, false, douyin_Image_init_zero, 0, {{NULL}, NULL}}
#define douyin_MatchAgainstScoreMessage_init_zero {false, douyin_Common_init_zero, false, douyin_Against_init_zero, 0, 0}
#define douyin_Against_init_zero                 {"", false, douyin_Image_init_zero, "", "", false, douyin_Image_init_zero, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define douyin_Common_init_zero                  {"", 0, 0, 0, 0, 0, "", 0, 0, 0, "", "", "", false, douyin_User_init_zero, 0, 0, 0, 0, 0, 0, 0}
#define douyin_User_init_zero                    {0, 0, "", 0, "", 0, 0, "", false, douyin_Image_init_zero, false, douyin_Image_init_zero, false, douyin_Image_init_zero, 0, 0, "", 0, 0, 0, 0, "", 0, {{NULL}, NULL}, false, douyin_FollowInfo_init_zero, "", false, douyin_Image_init_zero, false, douyin_Image_init_zero, {{NULL}, NULL}, "", "", 0, "", 0}
#define douyin_FollowInfo_init_zero              {0, 0, 0, 0, "", "", ""}
#define douyin_Image_init_zero                   {{{NULL}, NULL}, "", 0, 0, "", 0, "", false, douyin_ImageContent_init_zero, 0, false, douyin_NinePatchSetting_init_zero, false, douyin_NinePatchSetting_init_zero}
#define douyin_NinePatchSetting_init_zero        {{{NULL}, NULL}}
#define douyin_ImageContent_init_zero            {"", "", 0, ""}
#define douyin_PushFrame_init_zero               {0, 0, 0, 0, {{NULL}, NULL}, "", "", {{NULL}, NULL}}
#define douyin_kk_init_zero                      {0}
#define douyin_SendMessageBody_init_zero         {"", 0, 0, "", {{NULL}, NULL}, 0, "", ""}
#define douyin_ExtList_init_zero                 {"", ""}
#define douyin_Rsp_init_zero                     {0, 0, 0, "", 0, false, douyin_Rsp_F_init_zero, "", 0, 0, 0}
#define douyin_Rsp_F_init_zero                   {0, 0, "", 0}
#define douyin_PreMessage_init_zero              {0, 0, "", "", 0, 0, "", false, douyin_SendMessageBody_init_zero, "", "", {{NULL}, NULL}, 0, "", ""}
#define douyin_HeadersList_init_zero             {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define douyin_Response_messagesList_tag         1
#define douyin_Response_cursor_tag               2
#define douyin_Response_fetchInterval_tag        3
#define douyin_Response_now_tag                  4
#define douyin_Response_internalExt_tag          5
#define douyin_Response_fetchType_tag            6
#define douyin_Response_routeParams_tag          7
#define douyin_Response_heartbeatDuration_tag    8
#define douyin_Response_needAck_tag              9
#define douyin_Response_pushServer_tag           10
#define douyin_Response_liveCursor_tag           11
#define douyin_Response_historyNoMore_tag        12
#define douyin_Response_RouteParamsEntry_key_tag 1
#define douyin_Response_RouteParamsEntry_value_tag 2
#define douyin_Message_method_tag                1
#define douyin_Message_payload_tag               2
#define douyin_Message_msgId_tag                 3
#define douyin_Message_msgType_tag               4
#define douyin_Message_offset_tag                5
#define douyin_Message_needWrdsStore_tag         6
#define douyin_Message_wrdsVersion_tag           7
#define douyin_Message_wrdsSubKey_tag            8
#define douyin_LandscapeAreaCommon_showHead_tag  1
#define douyin_LandscapeAreaCommon_showNickname_tag 2
#define douyin_LandscapeAreaCommon_showFontColor_tag 3
#define douyin_LandscapeAreaCommon_colorValueList_tag 4
#define douyin_LandscapeAreaCommon_commentTypeTagsList_tag 5
#define douyin_GiftIMPriority_queueSizesList_tag 1
#define douyin_GiftIMPriority_selfQueuePriority_tag 2
#define douyin_GiftIMPriority_priority_tag       3
#define douyin_EffectConfig_ExtraMapEntry_key_tag 1
#define douyin_EffectConfig_ExtraMapEntry_value_tag 2
#define douyin_TextPiecePatternRef_key_tag       1
#define douyin_TextPiecePatternRef_defaultPattern_tag 2
#define douyin_TextPieceHeart_color_tag          1
#define douyin_PatternRef_key_tag                1
#define douyin_PatternRef_defaultPattern_tag     2
#define douyin_TextPieceGift_giftId_tag          1
#define douyin_TextPieceGift_nameRef_tag         2
#define douyin_TextFormat_color_tag              1
#define douyin_TextFormat_bold_tag               2
#define douyin_TextFormat_italic_tag             3
#define douyin_TextFormat_weight_tag             4
#define douyin_TextFormat_italicAngle_tag        5
#define douyin_TextFormat_fontSize_tag           6
#define douyin_TextFormat_useHeighLightColor_tag 7
#define douyin_TextFormat_useRemoteClor_tag      8
#define douyin_Text_key_tag                      1
#define douyin_Text_defaultPatter_tag            2
#define douyin_Text_defaultFormat_tag            3
#define douyin_Text_piecesList_tag               4
#define douyin_DoubleLikeDetail_doubleFlag_tag   1
#define douyin_DoubleLikeDetail_seqId_tag        2
#define douyin_DoubleLikeDetail_renewalsNum_tag  3
#define douyin_DoubleLikeDetail_triggersNum_tag  4
#define douyin_DisplayControlInfo_showText_tag   1
#define douyin_DisplayControlInfo_showIcons_tag  2
#define douyin_FollowInfo_followingCount_tag     1
#define douyin_FollowInfo_followerCount_tag      2
#define douyin_FollowInfo_followStatus_tag       3
#define douyin_FollowInfo_pushStatus_tag         4
#define douyin_FollowInfo_remarkName_tag         5
#define douyin_FollowInfo_followerCountStr_tag   6
#define douyin_FollowInfo_followingCountStr_tag  7
#define douyin_NinePatchSetting_settingListList_tag 1
#define douyin_ImageContent_name_tag             1
#define douyin_ImageContent_fontColor_tag        2
#define douyin_ImageContent_level_tag            3
#define douyin_ImageContent_alternativeText_tag  4
#define douyin_Image_urlListList_tag             1
#define douyin_Image_uri_tag                     2
#define douyin_Image_height_tag                  3
#define douyin_Image_width_tag                   4
#define douyin_Image_avgColor_tag                5
#define douyin_Image_imageType_tag               6
#define douyin_Image_openWebUrl_tag              7
#define douyin_Image_content_tag                 8
#define douyin_Image_isAnimated_tag              9
#define douyin_Image_FlexSettingList_tag         10
#define douyin_Image_TextSettingList_tag         11
#define douyin_GiftStruct_image_tag              1
#define douyin_GiftStruct_describe_tag           2
#define douyin_GiftStruct_notify_tag             3
#define douyin_GiftStruct_duration_tag           4
#define douyin_GiftStruct_id_tag                 5
#define douyin_GiftStruct_forLinkmic_tag         7
#define douyin_GiftStruct_doodle_tag             8
#define douyin_GiftStruct_forFansclub_tag        9
#define douyin_GiftStruct_combo_tag              10
#define douyin_GiftStruct_type_tag               11
#define douyin_GiftStruct_diamondCount_tag       12
#define douyin_GiftStruct_isDisplayedOnPanel_tag 13
#define douyin_GiftStruct_primaryEffectId_tag    14
#define douyin_GiftStruct_giftLabelIcon_tag      15
#define douyin_GiftStruct_name_tag               16
#define douyin_GiftStruct_region_tag             17
#define douyin_GiftStruct_manual_tag             18
#define douyin_GiftStruct_forCustom_tag          19
#define douyin_GiftStruct_icon_tag               21
#define douyin_GiftStruct_actionType_tag         22
#define douyin_TextEffectDetail_text_tag         1
#define douyin_TextEffectDetail_textFontSize_tag 2
#define douyin_TextEffectDetail_background_tag   3
#define douyin_TextEffectDetail_start_tag        4
#define douyin_TextEffectDetail_duration_tag     5
#define douyin_TextEffectDetail_x_tag            6
#define douyin_TextEffectDetail_y_tag            7
#define douyin_TextEffectDetail_width_tag        8
#define douyin_TextEffectDetail_height_tag       9
#define douyin_TextEffectDetail_shadowDx_tag     10
#define douyin_TextEffectDetail_shadowDy_tag     11
#define douyin_TextEffectDetail_shadowRadius_tag 12
#define douyin_TextEffectDetail_shadowColor_tag  13
#define douyin_TextEffectDetail_strokeColor_tag  14
#define douyin_TextEffectDetail_strokeWidth_tag  15
#define douyin_TextEffect_portrait_tag           1
#define douyin_TextEffect_landscape_tag          2
#define douyin_PublicAreaCommon_userLabel_tag    1
#define douyin_PublicAreaCommon_userConsumeInRoom_tag 2
#define douyin_PublicAreaCommon_userSendGiftCntInRoom_tag 3
#define douyin_EffectConfig_type_tag             1
#define douyin_EffectConfig_icon_tag             2
#define douyin_EffectConfig_avatarPos_tag        3
#define douyin_EffectConfig_text_tag             4
#define douyin_EffectConfig_textIcon_tag         5
#define douyin_EffectConfig_stayTime_tag         6
#define douyin_EffectConfig_animAssetId_tag      7
#define douyin_EffectConfig_badge_tag            8
#define douyin_EffectConfig_flexSettingArrayList_tag 9
#define douyin_EffectConfig_textIconOverlay_tag  10
#define douyin_EffectConfig_animatedBadge_tag    11
#define douyin_EffectConfig_hasSweepLight_tag    12
#define douyin_EffectConfig_textFlexSettingArrayList_tag 13
#define douyin_EffectConfig_centerAnimAssetId_tag 14
#define douyin_EffectConfig_dynamicImage_tag     15
#define douyin_EffectConfig_extraMap_tag         16
#define douyin_EffectConfig_mp4AnimAssetId_tag   17
#define douyin_EffectConfig_priority_tag         18
#define douyin_EffectConfig_maxWaitTime_tag      19
#define douyin_EffectConfig_dressId_tag          20
#define douyin_EffectConfig_alignment_tag        21
#define douyin_EffectConfig_alignmentOffset_tag  22
#define douyin_TextPieceImage_image_tag          1
#define douyin_TextPieceImage_scalingRate_tag    2
#define douyin_PicoDisplayInfo_comboSumCount_tag 1
#define douyin_PicoDisplayInfo_emoji_tag         2
#define douyin_PicoDisplayInfo_emojiIcon_tag     3
#define douyin_PicoDisplayInfo_emojiText_tag     4
#define douyin_Against_leftName_tag              1
#define douyin_Against_leftLogo_tag              2
#define douyin_Against_leftGoal_tag              3
#define douyin_Against_rightName_tag             6
#define douyin_Against_rightLogo_tag             7
#define douyin_Against_rightGoal_tag             8
#define douyin_Against_timestamp_tag             11
#define douyin_Against_version_tag               12
#define douyin_Against_leftTeamId_tag            13
#define douyin_Against_rightTeamId_tag           14
#define douyin_Against_diffSei2absSecond_tag     15
#define douyin_Against_finalGoalStage_tag        16
#define douyin_Against_currentGoalStage_tag      17
#define douyin_Against_leftScoreAddition_tag     18
#define douyin_Against_rightScoreAddition_tag    19
#define douyin_Against_leftGoalInt_tag           20
#define douyin_Against_rightGoalInt_tag          21
#define douyin_User_id_tag                       1
#define douyin_User_shortId_tag                  2
#define douyin_User_nickName_tag                 3
#define douyin_User_gender_tag                   4
#define douyin_User_Signature_tag                5
#define douyin_User_Level_tag                    6
#define douyin_User_Birthday_tag                 7
#define douyin_User_Telephone_tag                8
#define douyin_User_AvatarThumb_tag              9
#define douyin_User_AvatarMedium_tag             10
#define douyin_User_AvatarLarge_tag              11
#define douyin_User_Verified_tag                 12
#define douyin_User_Experience_tag               13
#define douyin_User_city_tag                     14
#define douyin_User_Status_tag                   15
#define douyin_User_CreateTime_tag               16
#define douyin_User_ModifyTime_tag               17
#define douyin_User_Secret_tag                   18
#define douyin_User_ShareQrcodeUri_tag           19
#define douyin_User_IncomeSharePercent_tag       20
#define douyin_User_BadgeImageList_tag           21
#define douyin_User_FollowInfo_tag               22
#define douyin_User_SpecialId_tag                26
#define douyin_User_AvatarBorder_tag             27
#define douyin_User_Medal_tag                    28
#define douyin_User_RealTimeIconsList_tag        29
#define douyin_User_displayId_tag                38
#define douyin_User_secUid_tag                   46
#define douyin_User_fanTicketCount_tag           1022
#define douyin_User_idStr_tag                    1028
#define douyin_User_ageRange_tag                 1045
#define douyin_RoomUserSeqMessageContributor_score_tag 1
#define douyin_RoomUserSeqMessageContributor_user_tag 2
#define douyin_RoomUserSeqMessageContributor_rank_tag 3
#define douyin_RoomUserSeqMessageContributor_delta_tag 4
#define douyin_RoomUserSeqMessageContributor_isHidden_tag 5
#define douyin_RoomUserSeqMessageContributor_scoreDescription_tag 6
#define douyin_RoomUserSeqMessageContributor_exactlyScore_tag 7
#define douyin_TextPieceUser_user_tag            1
#define douyin_TextPieceUser_withColon_tag       2
#define douyin_TextPiece_type_tag                1
#define douyin_TextPiece_format_tag              2
#define douyin_TextPiece_stringValue_tag         3
#define douyin_TextPiece_userValue_tag           4
#define douyin_TextPiece_giftValue_tag           5
#define douyin_TextPiece_heartValue_tag          6
#define douyin_TextPiece_patternRefValue_tag     7
#define douyin_TextPiece_imageValue_tag          8
#define douyin_EpisodeChatMessage_common_tag     1
#define douyin_EpisodeChatMessage_user_tag       2
#define douyin_EpisodeChatMessage_content_tag    3
#define douyin_EpisodeChatMessage_visibleToSende_tag 4
#define douyin_EpisodeChatMessage_giftImage_tag  7
#define douyin_EpisodeChatMessage_agreeMsgId_tag 8
#define douyin_EpisodeChatMessage_colorValueList_tag 9
#define douyin_Common_method_tag                 1
#define douyin_Common_msgId_tag                  2
#define douyin_Common_roomId_tag                 3
#define douyin_Common_createTime_tag             4
#define douyin_Common_monitor_tag                5
#define douyin_Common_isShowMsg_tag              6
#define douyin_Common_describe_tag               7
#define douyin_Common_foldType_tag               9
#define douyin_Common_anchorFoldType_tag         10
#define douyin_Common_priorityScore_tag          11
#define douyin_Common_logId_tag                  12
#define douyin_Common_msgProcessFilterK_tag      13
#define douyin_Common_msgProcessFilterV_tag      14
#define douyin_Common_user_tag                   15
#define douyin_Common_anchorFoldTypeV2_tag       17
#define douyin_Common_processAtSeiTimeMs_tag     18
#define douyin_Common_randomDispatchMs_tag       19
#define douyin_Common_isDispatch_tag             20
#define douyin_Common_channelId_tag              21
#define douyin_Common_diffSei2absSecond_tag      22
#define douyin_Common_anchorFoldDuration_tag     23
#define douyin_ChatMessage_common_tag            1
#define douyin_ChatMessage_user_tag              2
#define douyin_ChatMessage_content_tag           3
#define douyin_ChatMessage_visibleToSender_tag   4
#define douyin_ChatMessage_backgroundImage_tag   5
#define douyin_ChatMessage_fullScreenTextColor_tag 6
#define douyin_ChatMessage_backgroundImageV2_tag 7
#define douyin_ChatMessage_publicAreaCommon_tag  8
#define douyin_ChatMessage_giftImage_tag         9
#define douyin_ChatMessage_agreeMsgId_tag        11
#define douyin_ChatMessage_priorityLevel_tag     12
#define douyin_ChatMessage_landscapeAreaCommon_tag 13
#define douyin_ChatMessage_eventTime_tag         15
#define douyin_ChatMessage_sendReview_tag        16
#define douyin_ChatMessage_fromIntercom_tag      17
#define douyin_ChatMessage_intercomHideUserCard_tag 18
#define douyin_ChatMessage_chatBy_tag            20
#define douyin_ChatMessage_individualChatPriority_tag 21
#define douyin_ChatMessage_rtfContent_tag        22
#define douyin_RoomUserSeqMessage_common_tag     1
#define douyin_RoomUserSeqMessage_ranksList_tag  2
#define douyin_RoomUserSeqMessage_total_tag      3
#define douyin_RoomUserSeqMessage_popStr_tag     4
#define douyin_RoomUserSeqMessage_seatsList_tag  5
#define douyin_RoomUserSeqMessage_popularity_tag 6
#define douyin_RoomUserSeqMessage_totalUser_tag  7
#define douyin_RoomUserSeqMessage_totalUserStr_tag 8
#define douyin_RoomUserSeqMessage_totalStr_tag   9
#define douyin_RoomUserSeqMessage_onlineUserForAnchor_tag 10
#define douyin_RoomUserSeqMessage_totalPvForAnchor_tag 11
#define douyin_RoomUserSeqMessage_upRightStatsStr_tag 12
#define douyin_RoomUserSeqMessage_upRightStatsStrComplete_tag 13
#define douyin_CommonTextMessage_common_tag      1
#define douyin_CommonTextMessage_user_tag        2
#define douyin_CommonTextMessage_scene_tag       3
#define douyin_UpdateFanTicketMessage_common_tag 1
#define douyin_UpdateFanTicketMessage_roomFanTicketCountText_tag 2
#define douyin_UpdateFanTicketMessage_roomFanTicketCount_tag 3
#define douyin_UpdateFanTicketMessage_forceUpdate_tag 4
#define douyin_GiftMessage_common_tag            1
#define douyin_GiftMessage_giftId_tag            2
#define douyin_GiftMessage_fanTicketCount_tag    3
#define douyin_GiftMessage_groupCount_tag        4
#define douyin_GiftMessage_repeatCount_tag       5
#define douyin_GiftMessage_comboCount_tag        6
#define douyin_GiftMessage_user_tag              7
#define douyin_GiftMessage_toUser_tag            8
#define douyin_GiftMessage_repeatEnd_tag         9
#define douyin_GiftMessage_textEffect_tag        10
#define douyin_GiftMessage_groupId_tag           11
#define douyin_GiftMessage_incomeTaskgifts_tag   12
#define douyin_GiftMessage_roomFanTicketCount_tag 13
#define douyin_GiftMessage_priority_tag          14
#define douyin_GiftMessage_gift_tag              15
#define douyin_GiftMessage_logId_tag             16
#define douyin_GiftMessage_sendType_tag          17
#define douyin_GiftMessage_publicAreaCommon_tag  18
#define douyin_GiftMessage_trayDisplayText_tag   19
#define douyin_GiftMessage_bannedDisplayEffects_tag 20
#define douyin_GiftMessage_displayForSelf_tag    25
#define douyin_GiftMessage_interactGiftInfo_tag  26
#define douyin_GiftMessage_diyItemInfo_tag       27
#define douyin_GiftMessage_minAssetSetList_tag   28
#define douyin_GiftMessage_totalCount_tag        29
#define douyin_GiftMessage_clientGiftSource_tag  30
#define douyin_GiftMessage_toUserIdsList_tag     32
#define douyin_GiftMessage_sendTime_tag          33
#define douyin_GiftMessage_forceDisplayEffects_tag 34
#define douyin_GiftMessage_traceId_tag           35
#define douyin_GiftMessage_effectDisplayTs_tag   36
#define douyin_MemberMessage_common_tag          1
#define douyin_MemberMessage_user_tag            2
#define douyin_MemberMessage_memberCount_tag     3
#define douyin_MemberMessage_operator__tag       4
#define douyin_MemberMessage_isSetToAdmin_tag    5
#define douyin_MemberMessage_isTopUser_tag       6
#define douyin_MemberMessage_rankScore_tag       7
#define douyin_MemberMessage_topUserNo_tag       8
#define douyin_MemberMessage_enterType_tag       9
#define douyin_MemberMessage_action_tag          10
#define douyin_MemberMessage_actionDescription_tag 11
#define douyin_MemberMessage_userId_tag          12
#define douyin_MemberMessage_effectConfig_tag    13
#define douyin_MemberMessage_popStr_tag          14
#define douyin_MemberMessage_enterEffectConfig_tag 15
#define douyin_MemberMessage_backgroundImage_tag 16
#define douyin_MemberMessage_backgroundImageV2_tag 17
#define douyin_MemberMessage_anchorDisplayText_tag 18
#define douyin_MemberMessage_publicAreaCommon_tag 19
#define douyin_MemberMessage_userEnterTipType_tag 20
#define douyin_MemberMessage_anchorEnterTipType_tag 21
#define douyin_LikeMessage_common_tag            1
#define douyin_LikeMessage_count_tag             2
#define douyin_LikeMessage_total_tag             3
#define douyin_LikeMessage_color_tag             4
#define douyin_LikeMessage_user_tag              5
#define douyin_LikeMessage_icon_tag              6
#define douyin_LikeMessage_doubleLikeDetail_tag  7
#define douyin_LikeMessage_displayControlInfo_tag 8
#define douyin_LikeMessage_linkmicGuestUid_tag   9
#define douyin_LikeMessage_scene_tag             10
#define douyin_LikeMessage_picoDisplayInfo_tag   11
#define douyin_SocialMessage_common_tag          1
#define douyin_SocialMessage_user_tag            2
#define douyin_SocialMessage_shareType_tag       3
#define douyin_SocialMessage_action_tag          4
#define douyin_SocialMessage_shareTarget_tag     5
#define douyin_SocialMessage_followCount_tag     6
#define douyin_SocialMessage_publicAreaCommon_tag 7
#define douyin_MatchAgainstScoreMessage_common_tag 1
#define douyin_MatchAgainstScoreMessage_against_tag 2
#define douyin_MatchAgainstScoreMessage_matchStatus_tag 3
#define douyin_MatchAgainstScoreMessage_displayStatus_tag 4
#define douyin_PushFrame_seqId_tag               1
#define douyin_PushFrame_logId_tag               2
#define douyin_PushFrame_service_tag             3
#define douyin_PushFrame_method_tag              4
#define douyin_PushFrame_headersList_tag         5
#define douyin_PushFrame_payloadEncoding_tag     6
#define douyin_PushFrame_payloadType_tag         7
#define douyin_PushFrame_payload_tag             8
#define douyin_kk_k_tag                          14
#define douyin_SendMessageBody_conversationId_tag 1
#define douyin_SendMessageBody_conversationType_tag 2
#define douyin_SendMessageBody_conversationShortId_tag 3
#define douyin_SendMessageBody_content_tag       4
#define douyin_SendMessageBody_ext_tag           5
#define douyin_SendMessageBody_messageType_tag   6
#define douyin_SendMessageBody_ticket_tag        7
#define douyin_SendMessageBody_clientMessageId_tag 8
#define douyin_ExtList_key_tag                   1
#define douyin_ExtList_value_tag                 2
#define douyin_Rsp_F_q1_tag                      1
#define douyin_Rsp_F_q3_tag                      3
#define douyin_Rsp_F_q4_tag                      4
#define douyin_Rsp_F_q5_tag                      5
#define douyin_Rsp_a_tag                         1
#define douyin_Rsp_b_tag                         2
#define douyin_Rsp_c_tag                         3
#define douyin_Rsp_d_tag                         4
#define douyin_Rsp_e_tag                         5
#define douyin_Rsp_f_tag                         6
#define douyin_Rsp_g_tag                         7
#define douyin_Rsp_h_tag                         10
#define douyin_Rsp_i_tag                         11
#define douyin_Rsp_j_tag                         13
#define douyin_PreMessage_cmd_tag                1
#define douyin_PreMessage_sequenceId_tag         2
#define douyin_PreMessage_sdkVersion_tag         3
#define douyin_PreMessage_token_tag              4
#define douyin_PreMessage_refer_tag              5
#define douyin_PreMessage_inboxType_tag          6
#define douyin_PreMessage_buildNumber_tag        7
#define douyin_PreMessage_sendMessageBody_tag    8
#define douyin_PreMessage_aa_tag                 9
#define douyin_PreMessage_devicePlatform_tag     11
#define douyin_PreMessage_headers_tag            15
#define douyin_PreMessage_authType_tag           18
#define douyin_PreMessage_biz_tag                21
#define douyin_PreMessage_access_tag             22
#define douyin_HeadersList_key_tag               1
#define douyin_HeadersList_value_tag             2

/* Struct field encoding specification for nanopb */
#define douyin_Response_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  messagesList,      1) \
X(a, STATIC,   SINGULAR, STRING,   cursor,            2) \
X(a, STATIC,   SINGULAR, UINT64,   fetchInterval,     3) \
X(a, STATIC,   SINGULAR, UINT64,   now,               4) \
X(a, STATIC,   SINGULAR, STRING,   internalExt,       5) \
X(a, STATIC,   SINGULAR, UINT32,   fetchType,         6) \
X(a, CALLBACK, REPEATED, MESSAGE,  routeParams,       7) \
X(a, STATIC,   SINGULAR, UINT64,   heartbeatDuration,   8) \
X(a, STATIC,   SINGULAR, BOOL,     needAck,           9) \
X(a, STATIC,   SINGULAR, STRING,   pushServer,       10) \
X(a, STATIC,   SINGULAR, STRING,   liveCursor,       11) \
X(a, STATIC,   SINGULAR, BOOL,     historyNoMore,    12)
#define douyin_Response_CALLBACK pb_default_field_callback
#define douyin_Response_DEFAULT NULL
#define douyin_Response_messagesList_MSGTYPE douyin_Message
#define douyin_Response_routeParams_MSGTYPE douyin_Response_RouteParamsEntry

#define douyin_Response_RouteParamsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define douyin_Response_RouteParamsEntry_CALLBACK pb_default_field_callback
#define douyin_Response_RouteParamsEntry_DEFAULT NULL

#define douyin_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   method,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           2) \
X(a, STATIC,   SINGULAR, INT64,    msgId,             3) \
X(a, STATIC,   SINGULAR, INT32,    msgType,           4) \
X(a, STATIC,   SINGULAR, INT64,    offset,            5) \
X(a, STATIC,   SINGULAR, BOOL,     needWrdsStore,     6) \
X(a, STATIC,   SINGULAR, INT64,    wrdsVersion,       7) \
X(a, STATIC,   SINGULAR, STRING,   wrdsSubKey,        8)
#define douyin_Message_CALLBACK pb_default_field_callback
#define douyin_Message_DEFAULT NULL

#define douyin_ChatMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              2) \
X(a, STATIC,   SINGULAR, STRING,   content,           3) \
X(a, STATIC,   SINGULAR, BOOL,     visibleToSender,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  backgroundImage,   5) \
X(a, STATIC,   SINGULAR, STRING,   fullScreenTextColor,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  backgroundImageV2,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  publicAreaCommon,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  giftImage,         9) \
X(a, STATIC,   SINGULAR, UINT64,   agreeMsgId,       11) \
X(a, STATIC,   SINGULAR, UINT32,   priorityLevel,    12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  landscapeAreaCommon,  13) \
X(a, STATIC,   SINGULAR, UINT64,   eventTime,        15) \
X(a, STATIC,   SINGULAR, BOOL,     sendReview,       16) \
X(a, STATIC,   SINGULAR, BOOL,     fromIntercom,     17) \
X(a, STATIC,   SINGULAR, BOOL,     intercomHideUserCard,  18) \
X(a, STATIC,   SINGULAR, STRING,   chatBy,           20) \
X(a, STATIC,   SINGULAR, UINT32,   individualChatPriority,  21) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rtfContent,       22)
#define douyin_ChatMessage_CALLBACK NULL
#define douyin_ChatMessage_DEFAULT NULL
#define douyin_ChatMessage_common_MSGTYPE douyin_Common
#define douyin_ChatMessage_user_MSGTYPE douyin_User
#define douyin_ChatMessage_backgroundImage_MSGTYPE douyin_Image
#define douyin_ChatMessage_backgroundImageV2_MSGTYPE douyin_Image
#define douyin_ChatMessage_publicAreaCommon_MSGTYPE douyin_PublicAreaCommon
#define douyin_ChatMessage_giftImage_MSGTYPE douyin_Image
#define douyin_ChatMessage_landscapeAreaCommon_MSGTYPE douyin_LandscapeAreaCommon
#define douyin_ChatMessage_rtfContent_MSGTYPE douyin_Text

#define douyin_LandscapeAreaCommon_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     showHead,          1) \
X(a, STATIC,   SINGULAR, BOOL,     showNickname,      2) \
X(a, STATIC,   SINGULAR, BOOL,     showFontColor,     3) \
X(a, CALLBACK, REPEATED, STRING,   colorValueList,    4) \
X(a, CALLBACK, REPEATED, UENUM,    commentTypeTagsList,   5)
#define douyin_LandscapeAreaCommon_CALLBACK pb_default_field_callback
#define douyin_LandscapeAreaCommon_DEFAULT NULL

#define douyin_RoomUserSeqMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  ranksList,         2) \
X(a, STATIC,   SINGULAR, INT64,    total,             3) \
X(a, STATIC,   SINGULAR, STRING,   popStr,            4) \
X(a, CALLBACK, REPEATED, MESSAGE,  seatsList,         5) \
X(a, STATIC,   SINGULAR, INT64,    popularity,        6) \
X(a, STATIC,   SINGULAR, INT64,    totalUser,         7) \
X(a, STATIC,   SINGULAR, STRING,   totalUserStr,      8) \
X(a, STATIC,   SINGULAR, STRING,   totalStr,          9) \
X(a, STATIC,   SINGULAR, STRING,   onlineUserForAnchor,  10) \
X(a, STATIC,   SINGULAR, STRING,   totalPvForAnchor,  11) \
X(a, STATIC,   SINGULAR, STRING,   upRightStatsStr,  12) \
X(a, STATIC,   SINGULAR, STRING,   upRightStatsStrComplete,  13)
#define douyin_RoomUserSeqMessage_CALLBACK pb_default_field_callback
#define douyin_RoomUserSeqMessage_DEFAULT NULL
#define douyin_RoomUserSeqMessage_common_MSGTYPE douyin_Common
#define douyin_RoomUserSeqMessage_ranksList_MSGTYPE douyin_RoomUserSeqMessageContributor
#define douyin_RoomUserSeqMessage_seatsList_MSGTYPE douyin_RoomUserSeqMessageContributor

#define douyin_CommonTextMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              2) \
X(a, STATIC,   SINGULAR, STRING,   scene,             3)
#define douyin_CommonTextMessage_CALLBACK NULL
#define douyin_CommonTextMessage_DEFAULT NULL
#define douyin_CommonTextMessage_common_MSGTYPE douyin_Common
#define douyin_CommonTextMessage_user_MSGTYPE douyin_User

#define douyin_UpdateFanTicketMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, STRING,   roomFanTicketCountText,   2) \
X(a, STATIC,   SINGULAR, UINT64,   roomFanTicketCount,   3) \
X(a, STATIC,   SINGULAR, BOOL,     forceUpdate,       4)
#define douyin_UpdateFanTicketMessage_CALLBACK NULL
#define douyin_UpdateFanTicketMessage_DEFAULT NULL
#define douyin_UpdateFanTicketMessage_common_MSGTYPE douyin_Common

#define douyin_RoomUserSeqMessageContributor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   score,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              2) \
X(a, STATIC,   SINGULAR, UINT64,   rank,              3) \
X(a, STATIC,   SINGULAR, UINT64,   delta,             4) \
X(a, STATIC,   SINGULAR, BOOL,     isHidden,          5) \
X(a, STATIC,   SINGULAR, STRING,   scoreDescription,   6) \
X(a, STATIC,   SINGULAR, STRING,   exactlyScore,      7)
#define douyin_RoomUserSeqMessageContributor_CALLBACK NULL
#define douyin_RoomUserSeqMessageContributor_DEFAULT NULL
#define douyin_RoomUserSeqMessageContributor_user_MSGTYPE douyin_User

#define douyin_GiftMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, UINT64,   giftId,            2) \
X(a, STATIC,   SINGULAR, UINT64,   fanTicketCount,    3) \
X(a, STATIC,   SINGULAR, UINT64,   groupCount,        4) \
X(a, STATIC,   SINGULAR, UINT64,   repeatCount,       5) \
X(a, STATIC,   SINGULAR, UINT64,   comboCount,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  toUser,            8) \
X(a, STATIC,   SINGULAR, UINT32,   repeatEnd,         9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  textEffect,       10) \
X(a, STATIC,   SINGULAR, UINT64,   groupId,          11) \
X(a, STATIC,   SINGULAR, UINT64,   incomeTaskgifts,  12) \
X(a, STATIC,   SINGULAR, UINT64,   roomFanTicketCount,  13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  priority,         14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gift,             15) \
X(a, STATIC,   SINGULAR, STRING,   logId,            16) \
X(a, STATIC,   SINGULAR, UINT64,   sendType,         17) \
X(a, STATIC,   OPTIONAL, MESSAGE,  publicAreaCommon,  18) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trayDisplayText,  19) \
X(a, STATIC,   SINGULAR, UINT64,   bannedDisplayEffects,  20) \
X(a, STATIC,   SINGULAR, BOOL,     displayForSelf,   25) \
X(a, STATIC,   SINGULAR, STRING,   interactGiftInfo,  26) \
X(a, STATIC,   SINGULAR, STRING,   diyItemInfo,      27) \
X(a, CALLBACK, REPEATED, UINT64,   minAssetSetList,  28) \
X(a, STATIC,   SINGULAR, UINT64,   totalCount,       29) \
X(a, STATIC,   SINGULAR, UINT32,   clientGiftSource,  30) \
X(a, CALLBACK, REPEATED, UINT64,   toUserIdsList,    32) \
X(a, STATIC,   SINGULAR, UINT64,   sendTime,         33) \
X(a, STATIC,   SINGULAR, UINT64,   forceDisplayEffects,  34) \
X(a, STATIC,   SINGULAR, STRING,   traceId,          35) \
X(a, STATIC,   SINGULAR, UINT64,   effectDisplayTs,  36)
#define douyin_GiftMessage_CALLBACK pb_default_field_callback
#define douyin_GiftMessage_DEFAULT NULL
#define douyin_GiftMessage_common_MSGTYPE douyin_Common
#define douyin_GiftMessage_user_MSGTYPE douyin_User
#define douyin_GiftMessage_toUser_MSGTYPE douyin_User
#define douyin_GiftMessage_textEffect_MSGTYPE douyin_TextEffect
#define douyin_GiftMessage_priority_MSGTYPE douyin_GiftIMPriority
#define douyin_GiftMessage_gift_MSGTYPE douyin_GiftStruct
#define douyin_GiftMessage_publicAreaCommon_MSGTYPE douyin_PublicAreaCommon
#define douyin_GiftMessage_trayDisplayText_MSGTYPE douyin_Text

#define douyin_GiftStruct_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  image,             1) \
X(a, STATIC,   SINGULAR, STRING,   describe,          2) \
X(a, STATIC,   SINGULAR, BOOL,     notify,            3) \
X(a, STATIC,   SINGULAR, UINT64,   duration,          4) \
X(a, STATIC,   SINGULAR, UINT64,   id,                5) \
X(a, STATIC,   SINGULAR, BOOL,     forLinkmic,        7) \
X(a, STATIC,   SINGULAR, BOOL,     doodle,            8) \
X(a, STATIC,   SINGULAR, BOOL,     forFansclub,       9) \
X(a, STATIC,   SINGULAR, BOOL,     combo,            10) \
X(a, STATIC,   SINGULAR, UINT32,   type,             11) \
X(a, STATIC,   SINGULAR, UINT32,   diamondCount,     12) \
X(a, STATIC,   SINGULAR, BOOL,     isDisplayedOnPanel,  13) \
X(a, STATIC,   SINGULAR, UINT64,   primaryEffectId,  14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  giftLabelIcon,    15) \
X(a, STATIC,   SINGULAR, STRING,   name,             16) \
X(a, STATIC,   SINGULAR, STRING,   region,           17) \
X(a, STATIC,   SINGULAR, STRING,   manual,           18) \
X(a, STATIC,   SINGULAR, BOOL,     forCustom,        19) \
X(a, STATIC,   OPTIONAL, MESSAGE,  icon,             21) \
X(a, STATIC,   SINGULAR, UINT32,   actionType,       22)
#define douyin_GiftStruct_CALLBACK NULL
#define douyin_GiftStruct_DEFAULT NULL
#define douyin_GiftStruct_image_MSGTYPE douyin_Image
#define douyin_GiftStruct_giftLabelIcon_MSGTYPE douyin_Image
#define douyin_GiftStruct_icon_MSGTYPE douyin_Image

#define douyin_GiftIMPriority_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT64,   queueSizesList,    1) \
X(a, STATIC,   SINGULAR, UINT64,   selfQueuePriority,   2) \
X(a, STATIC,   SINGULAR, UINT64,   priority,          3)
#define douyin_GiftIMPriority_CALLBACK pb_default_field_callback
#define douyin_GiftIMPriority_DEFAULT NULL

#define douyin_TextEffect_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  portrait,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  landscape,         2)
#define douyin_TextEffect_CALLBACK NULL
#define douyin_TextEffect_DEFAULT NULL
#define douyin_TextEffect_portrait_MSGTYPE douyin_TextEffectDetail
#define douyin_TextEffect_landscape_MSGTYPE douyin_TextEffectDetail

#define douyin_TextEffectDetail_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  text,              1) \
X(a, STATIC,   SINGULAR, UINT32,   textFontSize,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  background,        3) \
X(a, STATIC,   SINGULAR, UINT32,   start,             4) \
X(a, STATIC,   SINGULAR, UINT32,   duration,          5) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 6) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 7) \
X(a, STATIC,   SINGULAR, UINT32,   width,             8) \
X(a, STATIC,   SINGULAR, UINT32,   height,            9) \
X(a, STATIC,   SINGULAR, UINT32,   shadowDx,         10) \
X(a, STATIC,   SINGULAR, UINT32,   shadowDy,         11) \
X(a, STATIC,   SINGULAR, UINT32,   shadowRadius,     12) \
X(a, STATIC,   SINGULAR, STRING,   shadowColor,      13) \
X(a, STATIC,   SINGULAR, STRING,   strokeColor,      14) \
X(a, STATIC,   SINGULAR, UINT32,   strokeWidth,      15)
#define douyin_TextEffectDetail_CALLBACK NULL
#define douyin_TextEffectDetail_DEFAULT NULL
#define douyin_TextEffectDetail_text_MSGTYPE douyin_Text
#define douyin_TextEffectDetail_background_MSGTYPE douyin_Image

#define douyin_MemberMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              2) \
X(a, STATIC,   SINGULAR, UINT64,   memberCount,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  operator_,         4) \
X(a, STATIC,   SINGULAR, BOOL,     isSetToAdmin,      5) \
X(a, STATIC,   SINGULAR, BOOL,     isTopUser,         6) \
X(a, STATIC,   SINGULAR, UINT64,   rankScore,         7) \
X(a, STATIC,   SINGULAR, UINT64,   topUserNo,         8) \
X(a, STATIC,   SINGULAR, UINT64,   enterType,         9) \
X(a, STATIC,   SINGULAR, UINT64,   action,           10) \
X(a, STATIC,   SINGULAR, STRING,   actionDescription,  11) \
X(a, STATIC,   SINGULAR, UINT64,   userId,           12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  effectConfig,     13) \
X(a, STATIC,   SINGULAR, STRING,   popStr,           14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enterEffectConfig,  15) \
X(a, STATIC,   OPTIONAL, MESSAGE,  backgroundImage,  16) \
X(a, STATIC,   OPTIONAL, MESSAGE,  backgroundImageV2,  17) \
X(a, STATIC,   OPTIONAL, MESSAGE,  anchorDisplayText,  18) \
X(a, STATIC,   OPTIONAL, MESSAGE,  publicAreaCommon,  19) \
X(a, STATIC,   SINGULAR, UINT64,   userEnterTipType,  20) \
X(a, STATIC,   SINGULAR, UINT64,   anchorEnterTipType,  21)
#define douyin_MemberMessage_CALLBACK NULL
#define douyin_MemberMessage_DEFAULT NULL
#define douyin_MemberMessage_common_MSGTYPE douyin_Common
#define douyin_MemberMessage_user_MSGTYPE douyin_User
#define douyin_MemberMessage_operator__MSGTYPE douyin_User
#define douyin_MemberMessage_effectConfig_MSGTYPE douyin_EffectConfig
#define douyin_MemberMessage_enterEffectConfig_MSGTYPE douyin_EffectConfig
#define douyin_MemberMessage_backgroundImage_MSGTYPE douyin_Image
#define douyin_MemberMessage_backgroundImageV2_MSGTYPE douyin_Image
#define douyin_MemberMessage_anchorDisplayText_MSGTYPE douyin_Text
#define douyin_MemberMessage_publicAreaCommon_MSGTYPE douyin_PublicAreaCommon

#define douyin_PublicAreaCommon_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  userLabel,         1) \
X(a, STATIC,   SINGULAR, UINT64,   userConsumeInRoom,   2) \
X(a, STATIC,   SINGULAR, UINT64,   userSendGiftCntInRoom,   3)
#define douyin_PublicAreaCommon_CALLBACK NULL
#define douyin_PublicAreaCommon_DEFAULT NULL
#define douyin_PublicAreaCommon_userLabel_MSGTYPE douyin_Image

#define douyin_EffectConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  icon,              2) \
X(a, STATIC,   SINGULAR, UINT64,   avatarPos,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  text,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  textIcon,          5) \
X(a, STATIC,   SINGULAR, UINT32,   stayTime,          6) \
X(a, STATIC,   SINGULAR, UINT64,   animAssetId,       7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  badge,             8) \
X(a, CALLBACK, REPEATED, UINT64,   flexSettingArrayList,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  textIconOverlay,  10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  animatedBadge,    11) \
X(a, STATIC,   SINGULAR, BOOL,     hasSweepLight,    12) \
X(a, CALLBACK, REPEATED, UINT64,   textFlexSettingArrayList,  13) \
X(a, STATIC,   SINGULAR, UINT64,   centerAnimAssetId,  14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dynamicImage,     15) \
X(a, CALLBACK, REPEATED, MESSAGE,  extraMap,         16) \
X(a, STATIC,   SINGULAR, UINT64,   mp4AnimAssetId,   17) \
X(a, STATIC,   SINGULAR, UINT64,   priority,         18) \
X(a, STATIC,   SINGULAR, UINT64,   maxWaitTime,      19) \
X(a, STATIC,   SINGULAR, STRING,   dressId,          20) \
X(a, STATIC,   SINGULAR, UINT64,   alignment,        21) \
X(a, STATIC,   SINGULAR, UINT64,   alignmentOffset,  22)
#define douyin_EffectConfig_CALLBACK pb_default_field_callback
#define douyin_EffectConfig_DEFAULT NULL
#define douyin_EffectConfig_icon_MSGTYPE douyin_Image
#define douyin_EffectConfig_text_MSGTYPE douyin_Text
#define douyin_EffectConfig_textIcon_MSGTYPE douyin_Image
#define douyin_EffectConfig_badge_MSGTYPE douyin_Image
#define douyin_EffectConfig_textIconOverlay_MSGTYPE douyin_Image
#define douyin_EffectConfig_animatedBadge_MSGTYPE douyin_Image
#define douyin_EffectConfig_dynamicImage_MSGTYPE douyin_Image
#define douyin_EffectConfig_extraMap_MSGTYPE douyin_EffectConfig_ExtraMapEntry

#define douyin_EffectConfig_ExtraMapEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define douyin_EffectConfig_ExtraMapEntry_CALLBACK pb_default_field_callback
#define douyin_EffectConfig_ExtraMapEntry_DEFAULT NULL

#define douyin_Text_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   defaultPatter,     2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  defaultFormat,     3) \
X(a, CALLBACK, REPEATED, MESSAGE,  piecesList,        4)
#define douyin_Text_CALLBACK pb_default_field_callback
#define douyin_Text_DEFAULT NULL
#define douyin_Text_defaultFormat_MSGTYPE douyin_TextFormat
#define douyin_Text_piecesList_MSGTYPE douyin_TextPiece

#define douyin_TextPiece_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  format,            2) \
X(a, STATIC,   SINGULAR, STRING,   stringValue,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  userValue,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  giftValue,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  heartValue,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  patternRefValue,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imageValue,        8)
#define douyin_TextPiece_CALLBACK NULL
#define douyin_TextPiece_DEFAULT NULL
#define douyin_TextPiece_format_MSGTYPE douyin_TextFormat
#define douyin_TextPiece_userValue_MSGTYPE douyin_TextPieceUser
#define douyin_TextPiece_giftValue_MSGTYPE douyin_TextPieceGift
#define douyin_TextPiece_heartValue_MSGTYPE douyin_TextPieceHeart
#define douyin_TextPiece_patternRefValue_MSGTYPE douyin_TextPiecePatternRef
#define douyin_TextPiece_imageValue_MSGTYPE douyin_TextPieceImage

#define douyin_TextPieceImage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  image,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    scalingRate,       2)
#define douyin_TextPieceImage_CALLBACK NULL
#define douyin_TextPieceImage_DEFAULT NULL
#define douyin_TextPieceImage_image_MSGTYPE douyin_Image

#define douyin_TextPiecePatternRef_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   defaultPattern,    2)
#define douyin_TextPiecePatternRef_CALLBACK NULL
#define douyin_TextPiecePatternRef_DEFAULT NULL

#define douyin_TextPieceHeart_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   color,             1)
#define douyin_TextPieceHeart_CALLBACK NULL
#define douyin_TextPieceHeart_DEFAULT NULL

#define douyin_TextPieceGift_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   giftId,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  nameRef,           2)
#define douyin_TextPieceGift_CALLBACK NULL
#define douyin_TextPieceGift_DEFAULT NULL
#define douyin_TextPieceGift_nameRef_MSGTYPE douyin_PatternRef

#define douyin_PatternRef_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   defaultPattern,    2)
#define douyin_PatternRef_CALLBACK NULL
#define douyin_PatternRef_DEFAULT NULL

#define douyin_TextPieceUser_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              1) \
X(a, STATIC,   SINGULAR, BOOL,     withColon,         2)
#define douyin_TextPieceUser_CALLBACK NULL
#define douyin_TextPieceUser_DEFAULT NULL
#define douyin_TextPieceUser_user_MSGTYPE douyin_User

#define douyin_TextFormat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   color,             1) \
X(a, STATIC,   SINGULAR, BOOL,     bold,              2) \
X(a, STATIC,   SINGULAR, BOOL,     italic,            3) \
X(a, STATIC,   SINGULAR, UINT32,   weight,            4) \
X(a, STATIC,   SINGULAR, UINT32,   italicAngle,       5) \
X(a, STATIC,   SINGULAR, UINT32,   fontSize,          6) \
X(a, STATIC,   SINGULAR, BOOL,     useHeighLightColor,   7) \
X(a, STATIC,   SINGULAR, BOOL,     useRemoteClor,     8)
#define douyin_TextFormat_CALLBACK NULL
#define douyin_TextFormat_DEFAULT NULL

#define douyin_LikeMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, UINT64,   count,             2) \
X(a, STATIC,   SINGULAR, UINT64,   total,             3) \
X(a, STATIC,   SINGULAR, UINT64,   color,             4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              5) \
X(a, STATIC,   SINGULAR, STRING,   icon,              6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  doubleLikeDetail,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  displayControlInfo,   8) \
X(a, STATIC,   SINGULAR, UINT64,   linkmicGuestUid,   9) \
X(a, STATIC,   SINGULAR, STRING,   scene,            10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  picoDisplayInfo,  11)
#define douyin_LikeMessage_CALLBACK NULL
#define douyin_LikeMessage_DEFAULT NULL
#define douyin_LikeMessage_common_MSGTYPE douyin_Common
#define douyin_LikeMessage_user_MSGTYPE douyin_User
#define douyin_LikeMessage_doubleLikeDetail_MSGTYPE douyin_DoubleLikeDetail
#define douyin_LikeMessage_displayControlInfo_MSGTYPE douyin_DisplayControlInfo
#define douyin_LikeMessage_picoDisplayInfo_MSGTYPE douyin_PicoDisplayInfo

#define douyin_SocialMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              2) \
X(a, STATIC,   SINGULAR, UINT64,   shareType,         3) \
X(a, STATIC,   SINGULAR, UINT64,   action,            4) \
X(a, STATIC,   SINGULAR, STRING,   shareTarget,       5) \
X(a, STATIC,   SINGULAR, UINT64,   followCount,       6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  publicAreaCommon,   7)
#define douyin_SocialMessage_CALLBACK NULL
#define douyin_SocialMessage_DEFAULT NULL
#define douyin_SocialMessage_common_MSGTYPE douyin_Common
#define douyin_SocialMessage_user_MSGTYPE douyin_User
#define douyin_SocialMessage_publicAreaCommon_MSGTYPE douyin_PublicAreaCommon

#define douyin_PicoDisplayInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   comboSumCount,     1) \
X(a, STATIC,   SINGULAR, STRING,   emoji,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  emojiIcon,         3) \
X(a, STATIC,   SINGULAR, STRING,   emojiText,         4)
#define douyin_PicoDisplayInfo_CALLBACK NULL
#define douyin_PicoDisplayInfo_DEFAULT NULL
#define douyin_PicoDisplayInfo_emojiIcon_MSGTYPE douyin_Image

#define douyin_DoubleLikeDetail_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     doubleFlag,        1) \
X(a, STATIC,   SINGULAR, UINT32,   seqId,             2) \
X(a, STATIC,   SINGULAR, UINT32,   renewalsNum,       3) \
X(a, STATIC,   SINGULAR, UINT32,   triggersNum,       4)
#define douyin_DoubleLikeDetail_CALLBACK NULL
#define douyin_DoubleLikeDetail_DEFAULT NULL

#define douyin_DisplayControlInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     showText,          1) \
X(a, STATIC,   SINGULAR, BOOL,     showIcons,         2)
#define douyin_DisplayControlInfo_CALLBACK NULL
#define douyin_DisplayControlInfo_DEFAULT NULL

#define douyin_EpisodeChatMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              2) \
X(a, STATIC,   SINGULAR, STRING,   content,           3) \
X(a, STATIC,   SINGULAR, BOOL,     visibleToSende,    4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  giftImage,         7) \
X(a, STATIC,   SINGULAR, UINT64,   agreeMsgId,        8) \
X(a, CALLBACK, REPEATED, STRING,   colorValueList,    9)
#define douyin_EpisodeChatMessage_CALLBACK pb_default_field_callback
#define douyin_EpisodeChatMessage_DEFAULT NULL
#define douyin_EpisodeChatMessage_common_MSGTYPE douyin_Message
#define douyin_EpisodeChatMessage_user_MSGTYPE douyin_User
#define douyin_EpisodeChatMessage_giftImage_MSGTYPE douyin_Image

#define douyin_MatchAgainstScoreMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  against,           2) \
X(a, STATIC,   SINGULAR, UINT32,   matchStatus,       3) \
X(a, STATIC,   SINGULAR, UINT32,   displayStatus,     4)
#define douyin_MatchAgainstScoreMessage_CALLBACK NULL
#define douyin_MatchAgainstScoreMessage_DEFAULT NULL
#define douyin_MatchAgainstScoreMessage_common_MSGTYPE douyin_Common
#define douyin_MatchAgainstScoreMessage_against_MSGTYPE douyin_Against

#define douyin_Against_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   leftName,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  leftLogo,          2) \
X(a, STATIC,   SINGULAR, STRING,   leftGoal,          3) \
X(a, STATIC,   SINGULAR, STRING,   rightName,         6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rightLogo,         7) \
X(a, STATIC,   SINGULAR, STRING,   rightGoal,         8) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,        11) \
X(a, STATIC,   SINGULAR, UINT64,   version,          12) \
X(a, STATIC,   SINGULAR, UINT64,   leftTeamId,       13) \
X(a, STATIC,   SINGULAR, UINT64,   rightTeamId,      14) \
X(a, STATIC,   SINGULAR, UINT64,   diffSei2absSecond,  15) \
X(a, STATIC,   SINGULAR, UINT32,   finalGoalStage,   16) \
X(a, STATIC,   SINGULAR, UINT32,   currentGoalStage,  17) \
X(a, STATIC,   SINGULAR, UINT32,   leftScoreAddition,  18) \
X(a, STATIC,   SINGULAR, UINT32,   rightScoreAddition,  19) \
X(a, STATIC,   SINGULAR, UINT64,   leftGoalInt,      20) \
X(a, STATIC,   SINGULAR, UINT64,   rightGoalInt,     21)
#define douyin_Against_CALLBACK NULL
#define douyin_Against_DEFAULT NULL
#define douyin_Against_leftLogo_MSGTYPE douyin_Image
#define douyin_Against_rightLogo_MSGTYPE douyin_Image

#define douyin_Common_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   method,            1) \
X(a, STATIC,   SINGULAR, UINT64,   msgId,             2) \
X(a, STATIC,   SINGULAR, UINT64,   roomId,            3) \
X(a, STATIC,   SINGULAR, UINT64,   createTime,        4) \
X(a, STATIC,   SINGULAR, UINT32,   monitor,           5) \
X(a, STATIC,   SINGULAR, BOOL,     isShowMsg,         6) \
X(a, STATIC,   SINGULAR, STRING,   describe,          7) \
X(a, STATIC,   SINGULAR, UINT64,   foldType,          9) \
X(a, STATIC,   SINGULAR, UINT64,   anchorFoldType,   10) \
X(a, STATIC,   SINGULAR, UINT64,   priorityScore,    11) \
X(a, STATIC,   SINGULAR, STRING,   logId,            12) \
X(a, STATIC,   SINGULAR, STRING,   msgProcessFilterK,  13) \
X(a, STATIC,   SINGULAR, STRING,   msgProcessFilterV,  14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,             15) \
X(a, STATIC,   SINGULAR, UINT64,   anchorFoldTypeV2,  17) \
X(a, STATIC,   SINGULAR, UINT64,   processAtSeiTimeMs,  18) \
X(a, STATIC,   SINGULAR, UINT64,   randomDispatchMs,  19) \
X(a, STATIC,   SINGULAR, BOOL,     isDispatch,       20) \
X(a, STATIC,   SINGULAR, UINT64,   channelId,        21) \
X(a, STATIC,   SINGULAR, UINT64,   diffSei2absSecond,  22) \
X(a, STATIC,   SINGULAR, UINT64,   anchorFoldDuration,  23)
#define douyin_Common_CALLBACK NULL
#define douyin_Common_DEFAULT NULL
#define douyin_Common_user_MSGTYPE douyin_User

#define douyin_User_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, UINT64,   shortId,           2) \
X(a, STATIC,   SINGULAR, STRING,   nickName,          3) \
X(a, STATIC,   SINGULAR, UINT32,   gender,            4) \
X(a, STATIC,   SINGULAR, STRING,   Signature,         5) \
X(a, STATIC,   SINGULAR, UINT32,   Level,             6) \
X(a, STATIC,   SINGULAR, UINT64,   Birthday,          7) \
X(a, STATIC,   SINGULAR, STRING,   Telephone,         8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  AvatarThumb,       9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  AvatarMedium,     10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  AvatarLarge,      11) \
X(a, STATIC,   SINGULAR, BOOL,     Verified,         12) \
X(a, STATIC,   SINGULAR, UINT32,   Experience,       13) \
X(a, STATIC,   SINGULAR, STRING,   city,             14) \
X(a, STATIC,   SINGULAR, INT32,    Status,           15) \
X(a, STATIC,   SINGULAR, UINT64,   CreateTime,       16) \
X(a, STATIC,   SINGULAR, UINT64,   ModifyTime,       17) \
X(a, STATIC,   SINGULAR, UINT32,   Secret,           18) \
X(a, STATIC,   SINGULAR, STRING,   ShareQrcodeUri,   19) \
X(a, STATIC,   SINGULAR, UINT32,   IncomeSharePercent,  20) \
X(a, CALLBACK, REPEATED, MESSAGE,  BadgeImageList,   21) \
X(a, STATIC,   OPTIONAL, MESSAGE,  FollowInfo,       22) \
X(a, STATIC,   SINGULAR, STRING,   SpecialId,        26) \
X(a, STATIC,   OPTIONAL, MESSAGE,  AvatarBorder,     27) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Medal,            28) \
X(a, CALLBACK, REPEATED, MESSAGE,  RealTimeIconsList,  29) \
X(a, STATIC,   SINGULAR, STRING,   displayId,        38) \
X(a, STATIC,   SINGULAR, STRING,   secUid,           46) \
X(a, STATIC,   SINGULAR, UINT64,   fanTicketCount,  1022) \
X(a, STATIC,   SINGULAR, STRING,   idStr,           1028) \
X(a, STATIC,   SINGULAR, UINT32,   ageRange,        1045)
#define douyin_User_CALLBACK pb_default_field_callback
#define douyin_User_DEFAULT NULL
#define douyin_User_AvatarThumb_MSGTYPE douyin_Image
#define douyin_User_AvatarMedium_MSGTYPE douyin_Image
#define douyin_User_AvatarLarge_MSGTYPE douyin_Image
#define douyin_User_BadgeImageList_MSGTYPE douyin_Image
#define douyin_User_FollowInfo_MSGTYPE douyin_FollowInfo
#define douyin_User_AvatarBorder_MSGTYPE douyin_Image
#define douyin_User_Medal_MSGTYPE douyin_Image
#define douyin_User_RealTimeIconsList_MSGTYPE douyin_Image

#define douyin_FollowInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   followingCount,    1) \
X(a, STATIC,   SINGULAR, UINT64,   followerCount,     2) \
X(a, STATIC,   SINGULAR, UINT64,   followStatus,      3) \
X(a, STATIC,   SINGULAR, UINT64,   pushStatus,        4) \
X(a, STATIC,   SINGULAR, STRING,   remarkName,        5) \
X(a, STATIC,   SINGULAR, STRING,   followerCountStr,   6) \
X(a, STATIC,   SINGULAR, STRING,   followingCountStr,   7)
#define douyin_FollowInfo_CALLBACK NULL
#define douyin_FollowInfo_DEFAULT NULL

#define douyin_Image_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   urlListList,       1) \
X(a, STATIC,   SINGULAR, STRING,   uri,               2) \
X(a, STATIC,   SINGULAR, UINT64,   height,            3) \
X(a, STATIC,   SINGULAR, UINT64,   width,             4) \
X(a, STATIC,   SINGULAR, STRING,   avgColor,          5) \
X(a, STATIC,   SINGULAR, UINT32,   imageType,         6) \
X(a, STATIC,   SINGULAR, STRING,   openWebUrl,        7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  content,           8) \
X(a, STATIC,   SINGULAR, BOOL,     isAnimated,        9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  FlexSettingList,  10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  TextSettingList,  11)
#define douyin_Image_CALLBACK pb_default_field_callback
#define douyin_Image_DEFAULT NULL
#define douyin_Image_content_MSGTYPE douyin_ImageContent
#define douyin_Image_FlexSettingList_MSGTYPE douyin_NinePatchSetting
#define douyin_Image_TextSettingList_MSGTYPE douyin_NinePatchSetting

#define douyin_NinePatchSetting_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   settingListList,   1)
#define douyin_NinePatchSetting_CALLBACK pb_default_field_callback
#define douyin_NinePatchSetting_DEFAULT NULL

#define douyin_ImageContent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   fontColor,         2) \
X(a, STATIC,   SINGULAR, UINT64,   level,             3) \
X(a, STATIC,   SINGULAR, STRING,   alternativeText,   4)
#define douyin_ImageContent_CALLBACK NULL
#define douyin_ImageContent_DEFAULT NULL

#define douyin_PushFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   seqId,             1) \
X(a, STATIC,   SINGULAR, UINT64,   logId,             2) \
X(a, STATIC,   SINGULAR, UINT64,   service,           3) \
X(a, STATIC,   SINGULAR, UINT64,   method,            4) \
X(a, CALLBACK, REPEATED, MESSAGE,  headersList,       5) \
X(a, STATIC,   SINGULAR, STRING,   payloadEncoding,   6) \
X(a, STATIC,   SINGULAR, STRING,   payloadType,       7) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           8)
#define douyin_PushFrame_CALLBACK pb_default_field_callback
#define douyin_PushFrame_DEFAULT NULL
#define douyin_PushFrame_headersList_MSGTYPE douyin_HeadersList

#define douyin_kk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   k,                14)
#define douyin_kk_CALLBACK NULL
#define douyin_kk_DEFAULT NULL

#define douyin_SendMessageBody_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   conversationId,    1) \
X(a, STATIC,   SINGULAR, UINT32,   conversationType,   2) \
X(a, STATIC,   SINGULAR, UINT64,   conversationShortId,   3) \
X(a, STATIC,   SINGULAR, STRING,   content,           4) \
X(a, CALLBACK, REPEATED, MESSAGE,  ext,               5) \
X(a, STATIC,   SINGULAR, UINT32,   messageType,       6) \
X(a, STATIC,   SINGULAR, STRING,   ticket,            7) \
X(a, STATIC,   SINGULAR, STRING,   clientMessageId,   8)
#define douyin_SendMessageBody_CALLBACK pb_default_field_callback
#define douyin_SendMessageBody_DEFAULT NULL
#define douyin_SendMessageBody_ext_MSGTYPE douyin_ExtList

#define douyin_ExtList_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define douyin_ExtList_CALLBACK NULL
#define douyin_ExtList_DEFAULT NULL

#define douyin_Rsp_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, INT32,    a,                 1) \
X(a_, STATIC,   SINGULAR, INT32,    b,                 2) \
X(a_, STATIC,   SINGULAR, INT32,    c,                 3) \
X(a_, STATIC,   SINGULAR, STRING,   d,                 4) \
X(a_, STATIC,   SINGULAR, INT32,    e,                 5) \
X(a_, STATIC,   OPTIONAL, MESSAGE,  f,                 6) \
X(a_, STATIC,   SINGULAR, STRING,   g,                 7) \
X(a_, STATIC,   SINGULAR, UINT64,   h,                10) \
X(a_, STATIC,   SINGULAR, UINT64,   i,                11) \
X(a_, STATIC,   SINGULAR, UINT64,   j,                13)
#define douyin_Rsp_CALLBACK NULL
#define douyin_Rsp_DEFAULT NULL
#define douyin_Rsp_f_MSGTYPE douyin_Rsp_F

#define douyin_Rsp_F_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   q1,                1) \
X(a, STATIC,   SINGULAR, UINT64,   q3,                3) \
X(a, STATIC,   SINGULAR, STRING,   q4,                4) \
X(a, STATIC,   SINGULAR, UINT64,   q5,                5)
#define douyin_Rsp_F_CALLBACK NULL
#define douyin_Rsp_F_DEFAULT NULL

#define douyin_PreMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cmd,               1) \
X(a, STATIC,   SINGULAR, UINT32,   sequenceId,        2) \
X(a, STATIC,   SINGULAR, STRING,   sdkVersion,        3) \
X(a, STATIC,   SINGULAR, STRING,   token,             4) \
X(a, STATIC,   SINGULAR, UINT32,   refer,             5) \
X(a, STATIC,   SINGULAR, UINT32,   inboxType,         6) \
X(a, STATIC,   SINGULAR, STRING,   buildNumber,       7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sendMessageBody,   8) \
X(a, STATIC,   SINGULAR, STRING,   aa,                9) \
X(a, STATIC,   SINGULAR, STRING,   devicePlatform,   11) \
X(a, CALLBACK, REPEATED, MESSAGE,  headers,          15) \
X(a, STATIC,   SINGULAR, UINT32,   authType,         18) \
X(a, STATIC,   SINGULAR, STRING,   biz,              21) \
X(a, STATIC,   SINGULAR, STRING,   access,           22)
#define douyin_PreMessage_CALLBACK pb_default_field_callback
#define douyin_PreMessage_DEFAULT NULL
#define douyin_PreMessage_sendMessageBody_MSGTYPE douyin_SendMessageBody
#define douyin_PreMessage_headers_MSGTYPE douyin_HeadersList

#define douyin_HeadersList_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define douyin_HeadersList_CALLBACK NULL
#define douyin_HeadersList_DEFAULT NULL

extern const pb_msgdesc_t douyin_Response_msg;
extern const pb_msgdesc_t douyin_Response_RouteParamsEntry_msg;
extern const pb_msgdesc_t douyin_Message_msg;
extern const pb_msgdesc_t douyin_ChatMessage_msg;
extern const pb_msgdesc_t douyin_LandscapeAreaCommon_msg;
extern const pb_msgdesc_t douyin_RoomUserSeqMessage_msg;
extern const pb_msgdesc_t douyin_CommonTextMessage_msg;
extern const pb_msgdesc_t douyin_UpdateFanTicketMessage_msg;
extern const pb_msgdesc_t douyin_RoomUserSeqMessageContributor_msg;
extern const pb_msgdesc_t douyin_GiftMessage_msg;
extern const pb_msgdesc_t douyin_GiftStruct_msg;
extern const pb_msgdesc_t douyin_GiftIMPriority_msg;
extern const pb_msgdesc_t douyin_TextEffect_msg;
extern const pb_msgdesc_t douyin_TextEffectDetail_msg;
extern const pb_msgdesc_t douyin_MemberMessage_msg;
extern const pb_msgdesc_t douyin_PublicAreaCommon_msg;
extern const pb_msgdesc_t douyin_EffectConfig_msg;
extern const pb_msgdesc_t douyin_EffectConfig_ExtraMapEntry_msg;
extern const pb_msgdesc_t douyin_Text_msg;
extern const pb_msgdesc_t douyin_TextPiece_msg;
extern const pb_msgdesc_t douyin_TextPieceImage_msg;
extern const pb_msgdesc_t douyin_TextPiecePatternRef_msg;
extern const pb_msgdesc_t douyin_TextPieceHeart_msg;
extern const pb_msgdesc_t douyin_TextPieceGift_msg;
extern const pb_msgdesc_t douyin_PatternRef_msg;
extern const pb_msgdesc_t douyin_TextPieceUser_msg;
extern const pb_msgdesc_t douyin_TextFormat_msg;
extern const pb_msgdesc_t douyin_LikeMessage_msg;
extern const pb_msgdesc_t douyin_SocialMessage_msg;
extern const pb_msgdesc_t douyin_PicoDisplayInfo_msg;
extern const pb_msgdesc_t douyin_DoubleLikeDetail_msg;
extern const pb_msgdesc_t douyin_DisplayControlInfo_msg;
extern const pb_msgdesc_t douyin_EpisodeChatMessage_msg;
extern const pb_msgdesc_t douyin_MatchAgainstScoreMessage_msg;
extern const pb_msgdesc_t douyin_Against_msg;
extern const pb_msgdesc_t douyin_Common_msg;
extern const pb_msgdesc_t douyin_User_msg;
extern const pb_msgdesc_t douyin_FollowInfo_msg;
extern const pb_msgdesc_t douyin_Image_msg;
extern const pb_msgdesc_t douyin_NinePatchSetting_msg;
extern const pb_msgdesc_t douyin_ImageContent_msg;
extern const pb_msgdesc_t douyin_PushFrame_msg;
extern const pb_msgdesc_t douyin_kk_msg;
extern const pb_msgdesc_t douyin_SendMessageBody_msg;
extern const pb_msgdesc_t douyin_ExtList_msg;
extern const pb_msgdesc_t douyin_Rsp_msg;
extern const pb_msgdesc_t douyin_Rsp_F_msg;
extern const pb_msgdesc_t douyin_PreMessage_msg;
extern const pb_msgdesc_t douyin_HeadersList_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define douyin_Response_fields &douyin_Response_msg
#define douyin_Response_RouteParamsEntry_fields &douyin_Response_RouteParamsEntry_msg
#define douyin_Message_fields &douyin_Message_msg
#define douyin_ChatMessage_fields &douyin_ChatMessage_msg
#define douyin_LandscapeAreaCommon_fields &douyin_LandscapeAreaCommon_msg
#define douyin_RoomUserSeqMessage_fields &douyin_RoomUserSeqMessage_msg
#define douyin_CommonTextMessage_fields &douyin_CommonTextMessage_msg
#define douyin_UpdateFanTicketMessage_fields &douyin_UpdateFanTicketMessage_msg
#define douyin_RoomUserSeqMessageContributor_fields &douyin_RoomUserSeqMessageContributor_msg
#define douyin_GiftMessage_fields &douyin_GiftMessage_msg
#define douyin_GiftStruct_fields &douyin_GiftStruct_msg
#define douyin_GiftIMPriority_fields &douyin_GiftIMPriority_msg
#define douyin_TextEffect_fields &douyin_TextEffect_msg
#define douyin_TextEffectDetail_fields &douyin_TextEffectDetail_msg
#define douyin_MemberMessage_fields &douyin_MemberMessage_msg
#define douyin_PublicAreaCommon_fields &douyin_PublicAreaCommon_msg
#define douyin_EffectConfig_fields &douyin_EffectConfig_msg
#define douyin_EffectConfig_ExtraMapEntry_fields &douyin_EffectConfig_ExtraMapEntry_msg
#define douyin_Text_fields &douyin_Text_msg
#define douyin_TextPiece_fields &douyin_TextPiece_msg
#define douyin_TextPieceImage_fields &douyin_TextPieceImage_msg
#define douyin_TextPiecePatternRef_fields &douyin_TextPiecePatternRef_msg
#define douyin_TextPieceHeart_fields &douyin_TextPieceHeart_msg
#define douyin_TextPieceGift_fields &douyin_TextPieceGift_msg
#define douyin_PatternRef_fields &douyin_PatternRef_msg
#define douyin_TextPieceUser_fields &douyin_TextPieceUser_msg
#define douyin_TextFormat_fields &douyin_TextFormat_msg
#define douyin_LikeMessage_fields &douyin_LikeMessage_msg
#define douyin_SocialMessage_fields &douyin_SocialMessage_msg
#define douyin_PicoDisplayInfo_fields &douyin_PicoDisplayInfo_msg
#define douyin_DoubleLikeDetail_fields &douyin_DoubleLikeDetail_msg
#define douyin_DisplayControlInfo_fields &douyin_DisplayControlInfo_msg
#define douyin_EpisodeChatMessage_fields &douyin_EpisodeChatMessage_msg
#define douyin_MatchAgainstScoreMessage_fields &douyin_MatchAgainstScoreMessage_msg
#define douyin_Against_fields &douyin_Against_msg
#define douyin_Common_fields &douyin_Common_msg
#define douyin_User_fields &douyin_User_msg
#define douyin_FollowInfo_fields &douyin_FollowInfo_msg
#define douyin_Image_fields &douyin_Image_msg
#define douyin_NinePatchSetting_fields &douyin_NinePatchSetting_msg
#define douyin_ImageContent_fields &douyin_ImageContent_msg
#define douyin_PushFrame_fields &douyin_PushFrame_msg
#define douyin_kk_fields &douyin_kk_msg
#define douyin_SendMessageBody_fields &douyin_SendMessageBody_msg
#define douyin_ExtList_fields &douyin_ExtList_msg
#define douyin_Rsp_fields &douyin_Rsp_msg
#define douyin_Rsp_F_fields &douyin_Rsp_F_msg
#define douyin_PreMessage_fields &douyin_PreMessage_msg
#define douyin_HeadersList_fields &douyin_HeadersList_msg

/* Maximum encoded size of messages (where known) */
/* douyin_Response_size depends on runtime parameters */
/* douyin_Response_RouteParamsEntry_size depends on runtime parameters */
/* douyin_Message_size depends on runtime parameters */
/* douyin_ChatMessage_size depends on runtime parameters */
/* douyin_LandscapeAreaCommon_size depends on runtime parameters */
/* douyin_RoomUserSeqMessage_size depends on runtime parameters */
/* douyin_CommonTextMessage_size depends on runtime parameters */
/* douyin_UpdateFanTicketMessage_size depends on runtime parameters */
/* douyin_RoomUserSeqMessageContributor_size depends on runtime parameters */
/* douyin_GiftMessage_size depends on runtime parameters */
/* douyin_GiftStruct_size depends on runtime parameters */
/* douyin_GiftIMPriority_size depends on runtime parameters */
/* douyin_TextEffect_size depends on runtime parameters */
/* douyin_TextEffectDetail_size depends on runtime parameters */
/* douyin_MemberMessage_size depends on runtime parameters */
/* douyin_PublicAreaCommon_size depends on runtime parameters */
/* douyin_EffectConfig_size depends on runtime parameters */
/* douyin_EffectConfig_ExtraMapEntry_size depends on runtime parameters */
/* douyin_Text_size depends on runtime parameters */
/* douyin_TextPiece_size depends on runtime parameters */
/* douyin_TextPieceImage_size depends on runtime parameters */
/* douyin_TextPieceUser_size depends on runtime parameters */
/* douyin_LikeMessage_size depends on runtime parameters */
/* douyin_SocialMessage_size depends on runtime parameters */
/* douyin_PicoDisplayInfo_size depends on runtime parameters */
/* douyin_EpisodeChatMessage_size depends on runtime parameters */
/* douyin_MatchAgainstScoreMessage_size depends on runtime parameters */
/* douyin_Against_size depends on runtime parameters */
/* douyin_Common_size depends on runtime parameters */
/* douyin_User_size depends on runtime parameters */
/* douyin_Image_size depends on runtime parameters */
/* douyin_NinePatchSetting_size depends on runtime parameters */
/* douyin_PushFrame_size depends on runtime parameters */
/* douyin_SendMessageBody_size depends on runtime parameters */
/* douyin_PreMessage_size depends on runtime parameters */
#define DOUYIN_DOUYIN_PB_H_MAX_SIZE              douyin_Rsp_size
#define douyin_DisplayControlInfo_size           4
#define douyin_DoubleLikeDetail_size             20
#define douyin_ExtList_size                      260
#define douyin_FollowInfo_size                   434
#define douyin_HeadersList_size                  260
#define douyin_ImageContent_size                 401
#define douyin_PatternRef_size                   260
#define douyin_Rsp_F_size                        163
#define douyin_Rsp_size                          503
#define douyin_TextFormat_size                   156
#define douyin_TextPieceGift_size                274
#define douyin_TextPieceHeart_size               130
#define douyin_TextPiecePatternRef_size          260
#define douyin_kk_size                           6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
