/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_INTERACT_WORD_V2_PB_H_INCLUDED
#define PB_INTERACT_WORD_V2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _InteractWordV2_FansMedal {
    uint64_t target_id;
    uint32_t medal_level;
    char medal_name[128];
    bool has_is_lighted;
    uint32_t is_lighted;
    bool has_guard_level;
    uint32_t guard_level;
    uint32_t room_id;
    uint32_t score;
} InteractWordV2_FansMedal;

typedef struct _InteractWordV2_RankInfo {
    uint32_t rank;
} InteractWordV2_RankInfo;

typedef struct _InteractWordV2_UserInfo_BaseInfo {
    char uname[128];
    char face[128];
    bool has_name_color_str;
    char name_color_str[128];
} InteractWordV2_UserInfo_BaseInfo;

typedef struct _InteractWordV2_UserInfo_MedalInfo {
    char medal_name[128];
    uint32_t medal_level;
    uint64_t ruid;
    uint32_t guard_level;
    char guard_icon[128];
    char v2_medal_color_start[128];
    char v2_medal_color_end[128];
    char v2_medal_color_border[128];
    char v2_medal_color_text[128];
    char v2_medal_color_level[128];
} InteractWordV2_UserInfo_MedalInfo;

typedef struct _InteractWordV2_UserInfo_WealthInfo {
    uint32_t level;
} InteractWordV2_UserInfo_WealthInfo;

typedef struct _InteractWordV2_UserInfo_GuardInfo {
    uint32_t level;
    char expired_str[128];
} InteractWordV2_UserInfo_GuardInfo;

typedef struct _InteractWordV2_UserInfo {
    uint64_t uid;
    bool has_base;
    InteractWordV2_UserInfo_BaseInfo base;
    bool has_medal_info;
    InteractWordV2_UserInfo_MedalInfo medal_info;
    bool has_wealth;
    InteractWordV2_UserInfo_WealthInfo wealth;
    bool has_guard;
    InteractWordV2_UserInfo_GuardInfo guard;
} InteractWordV2_UserInfo;

typedef struct _InteractWordV2 {
    uint64_t uid;
    char uname[128];
    uint32_t msg_type;
    uint32_t room_id;
    uint32_t timestamp;
    bool has_fans_medal;
    InteractWordV2_FansMedal fans_medal;
    bool has_rank_info;
    InteractWordV2_RankInfo rank_info;
    bool has_guard_level;
    uint32_t guard_level;
    bool has_uinfo;
    InteractWordV2_UserInfo uinfo;
} InteractWordV2;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define InteractWordV2_init_default              {0, "", 0, 0, 0, false, InteractWordV2_FansMedal_init_default, false, InteractWordV2_RankInfo_init_default, false, 0, false, InteractWordV2_UserInfo_init_default}
#define InteractWordV2_FansMedal_init_default    {0, 0, "", false, 0, false, 0, 0, 0}
#define InteractWordV2_RankInfo_init_default     {0}
#define InteractWordV2_UserInfo_init_default     {0, false, InteractWordV2_UserInfo_BaseInfo_init_default, false, InteractWordV2_UserInfo_MedalInfo_init_default, false, InteractWordV2_UserInfo_WealthInfo_init_default, false, InteractWordV2_UserInfo_GuardInfo_init_default}
#define InteractWordV2_UserInfo_BaseInfo_init_default {"", "", false, ""}
#define InteractWordV2_UserInfo_MedalInfo_init_default {"", 0, 0, 0, "", "", "", "", "", ""}
#define InteractWordV2_UserInfo_WealthInfo_init_default {0}
#define InteractWordV2_UserInfo_GuardInfo_init_default {0, ""}
#define InteractWordV2_init_zero                 {0, "", 0, 0, 0, false, InteractWordV2_FansMedal_init_zero, false, InteractWordV2_RankInfo_init_zero, false, 0, false, InteractWordV2_UserInfo_init_zero}
#define InteractWordV2_FansMedal_init_zero       {0, 0, "", false, 0, false, 0, 0, 0}
#define InteractWordV2_RankInfo_init_zero        {0}
#define InteractWordV2_UserInfo_init_zero        {0, false, InteractWordV2_UserInfo_BaseInfo_init_zero, false, InteractWordV2_UserInfo_MedalInfo_init_zero, false, InteractWordV2_UserInfo_WealthInfo_init_zero, false, InteractWordV2_UserInfo_GuardInfo_init_zero}
#define InteractWordV2_UserInfo_BaseInfo_init_zero {"", "", false, ""}
#define InteractWordV2_UserInfo_MedalInfo_init_zero {"", 0, 0, 0, "", "", "", "", "", ""}
#define InteractWordV2_UserInfo_WealthInfo_init_zero {0}
#define InteractWordV2_UserInfo_GuardInfo_init_zero {0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define InteractWordV2_FansMedal_target_id_tag   1
#define InteractWordV2_FansMedal_medal_level_tag 2
#define InteractWordV2_FansMedal_medal_name_tag  3
#define InteractWordV2_FansMedal_is_lighted_tag  8
#define InteractWordV2_FansMedal_guard_level_tag 9
#define InteractWordV2_FansMedal_room_id_tag     12
#define InteractWordV2_FansMedal_score_tag       13
#define InteractWordV2_RankInfo_rank_tag         1
#define InteractWordV2_UserInfo_BaseInfo_uname_tag 1
#define InteractWordV2_UserInfo_BaseInfo_face_tag 2
#define InteractWordV2_UserInfo_BaseInfo_name_color_str_tag 8
#define InteractWordV2_UserInfo_MedalInfo_medal_name_tag 1
#define InteractWordV2_UserInfo_MedalInfo_medal_level_tag 2
#define InteractWordV2_UserInfo_MedalInfo_ruid_tag 10
#define InteractWordV2_UserInfo_MedalInfo_guard_level_tag 11
#define InteractWordV2_UserInfo_MedalInfo_guard_icon_tag 13
#define InteractWordV2_UserInfo_MedalInfo_v2_medal_color_start_tag 15
#define InteractWordV2_UserInfo_MedalInfo_v2_medal_color_end_tag 16
#define InteractWordV2_UserInfo_MedalInfo_v2_medal_color_border_tag 17
#define InteractWordV2_UserInfo_MedalInfo_v2_medal_color_text_tag 18
#define InteractWordV2_UserInfo_MedalInfo_v2_medal_color_level_tag 19
#define InteractWordV2_UserInfo_WealthInfo_level_tag 1
#define InteractWordV2_UserInfo_GuardInfo_level_tag 1
#define InteractWordV2_UserInfo_GuardInfo_expired_str_tag 2
#define InteractWordV2_UserInfo_uid_tag          1
#define InteractWordV2_UserInfo_base_tag         2
#define InteractWordV2_UserInfo_medal_info_tag   3
#define InteractWordV2_UserInfo_wealth_tag       4
#define InteractWordV2_UserInfo_guard_tag        6
#define InteractWordV2_uid_tag                   1
#define InteractWordV2_uname_tag                 2
#define InteractWordV2_msg_type_tag              5
#define InteractWordV2_room_id_tag               6
#define InteractWordV2_timestamp_tag             7
#define InteractWordV2_fans_medal_tag            9
#define InteractWordV2_rank_info_tag             12
#define InteractWordV2_guard_level_tag           16
#define InteractWordV2_uinfo_tag                 22

/* Struct field encoding specification for nanopb */
#define InteractWordV2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   uid,               1) \
X(a, STATIC,   SINGULAR, STRING,   uname,             2) \
X(a, STATIC,   SINGULAR, UINT32,   msg_type,          5) \
X(a, STATIC,   SINGULAR, UINT32,   room_id,           6) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fans_medal,        9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rank_info,        12) \
X(a, STATIC,   OPTIONAL, UINT32,   guard_level,      16) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uinfo,            22)
#define InteractWordV2_CALLBACK NULL
#define InteractWordV2_DEFAULT NULL
#define InteractWordV2_fans_medal_MSGTYPE InteractWordV2_FansMedal
#define InteractWordV2_rank_info_MSGTYPE InteractWordV2_RankInfo
#define InteractWordV2_uinfo_MSGTYPE InteractWordV2_UserInfo

#define InteractWordV2_FansMedal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   target_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   medal_level,       2) \
X(a, STATIC,   SINGULAR, STRING,   medal_name,        3) \
X(a, STATIC,   OPTIONAL, UINT32,   is_lighted,        8) \
X(a, STATIC,   OPTIONAL, UINT32,   guard_level,       9) \
X(a, STATIC,   SINGULAR, UINT32,   room_id,          12) \
X(a, STATIC,   SINGULAR, UINT32,   score,            13)
#define InteractWordV2_FansMedal_CALLBACK NULL
#define InteractWordV2_FansMedal_DEFAULT NULL

#define InteractWordV2_RankInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rank,              1)
#define InteractWordV2_RankInfo_CALLBACK NULL
#define InteractWordV2_RankInfo_DEFAULT NULL

#define InteractWordV2_UserInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   uid,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  base,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  medal_info,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wealth,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  guard,             6)
#define InteractWordV2_UserInfo_CALLBACK NULL
#define InteractWordV2_UserInfo_DEFAULT NULL
#define InteractWordV2_UserInfo_base_MSGTYPE InteractWordV2_UserInfo_BaseInfo
#define InteractWordV2_UserInfo_medal_info_MSGTYPE InteractWordV2_UserInfo_MedalInfo
#define InteractWordV2_UserInfo_wealth_MSGTYPE InteractWordV2_UserInfo_WealthInfo
#define InteractWordV2_UserInfo_guard_MSGTYPE InteractWordV2_UserInfo_GuardInfo

#define InteractWordV2_UserInfo_BaseInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   uname,             1) \
X(a, STATIC,   SINGULAR, STRING,   face,              2) \
X(a, STATIC,   OPTIONAL, STRING,   name_color_str,    8)
#define InteractWordV2_UserInfo_BaseInfo_CALLBACK NULL
#define InteractWordV2_UserInfo_BaseInfo_DEFAULT NULL

#define InteractWordV2_UserInfo_MedalInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   medal_name,        1) \
X(a, STATIC,   SINGULAR, UINT32,   medal_level,       2) \
X(a, STATIC,   SINGULAR, UINT64,   ruid,             10) \
X(a, STATIC,   SINGULAR, UINT32,   guard_level,      11) \
X(a, STATIC,   SINGULAR, STRING,   guard_icon,       13) \
X(a, STATIC,   SINGULAR, STRING,   v2_medal_color_start,  15) \
X(a, STATIC,   SINGULAR, STRING,   v2_medal_color_end,  16) \
X(a, STATIC,   SINGULAR, STRING,   v2_medal_color_border,  17) \
X(a, STATIC,   SINGULAR, STRING,   v2_medal_color_text,  18) \
X(a, STATIC,   SINGULAR, STRING,   v2_medal_color_level,  19)
#define InteractWordV2_UserInfo_MedalInfo_CALLBACK NULL
#define InteractWordV2_UserInfo_MedalInfo_DEFAULT NULL

#define InteractWordV2_UserInfo_WealthInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   level,             1)
#define InteractWordV2_UserInfo_WealthInfo_CALLBACK NULL
#define InteractWordV2_UserInfo_WealthInfo_DEFAULT NULL

#define InteractWordV2_UserInfo_GuardInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   level,             1) \
X(a, STATIC,   SINGULAR, STRING,   expired_str,       2)
#define InteractWordV2_UserInfo_GuardInfo_CALLBACK NULL
#define InteractWordV2_UserInfo_GuardInfo_DEFAULT NULL

extern const pb_msgdesc_t InteractWordV2_msg;
extern const pb_msgdesc_t InteractWordV2_FansMedal_msg;
extern const pb_msgdesc_t InteractWordV2_RankInfo_msg;
extern const pb_msgdesc_t InteractWordV2_UserInfo_msg;
extern const pb_msgdesc_t InteractWordV2_UserInfo_BaseInfo_msg;
extern const pb_msgdesc_t InteractWordV2_UserInfo_MedalInfo_msg;
extern const pb_msgdesc_t InteractWordV2_UserInfo_WealthInfo_msg;
extern const pb_msgdesc_t InteractWordV2_UserInfo_GuardInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define InteractWordV2_fields &InteractWordV2_msg
#define InteractWordV2_FansMedal_fields &InteractWordV2_FansMedal_msg
#define InteractWordV2_RankInfo_fields &InteractWordV2_RankInfo_msg
#define InteractWordV2_UserInfo_fields &InteractWordV2_UserInfo_msg
#define InteractWordV2_UserInfo_BaseInfo_fields &InteractWordV2_UserInfo_BaseInfo_msg
#define InteractWordV2_UserInfo_MedalInfo_fields &InteractWordV2_UserInfo_MedalInfo_msg
#define InteractWordV2_UserInfo_WealthInfo_fields &InteractWordV2_UserInfo_WealthInfo_msg
#define InteractWordV2_UserInfo_GuardInfo_fields &InteractWordV2_UserInfo_GuardInfo_msg

/* Maximum encoded size of messages (where known) */
#define INTERACT_WORD_V2_PB_H_MAX_SIZE           InteractWordV2_size
#define InteractWordV2_FansMedal_size            171
#define InteractWordV2_RankInfo_size             6
#define InteractWordV2_UserInfo_BaseInfo_size    390
#define InteractWordV2_UserInfo_GuardInfo_size   136
#define InteractWordV2_UserInfo_MedalInfo_size   937
#define InteractWordV2_UserInfo_WealthInfo_size  6
#define InteractWordV2_UserInfo_size             1491
#define InteractWordV2_size                      1843

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
