/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "interact_word_v2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InteractWordV2, InteractWordV2, 2)


PB_BIND(InteractWordV2_FansMedal, InteractWordV2_FansMedal, AUTO)


PB_BIND(InteractWordV2_RankInfo, InteractWordV2_RankInfo, AUTO)


PB_BIND(InteractWordV2_UserInfo, InteractWordV2_UserInfo, 2)


PB_BIND(InteractWordV2_UserInfo_BaseInfo, InteractWordV2_UserInfo_BaseInfo, 2)


PB_BIND(InteractWordV2_UserInfo_BaseInfo_OriginInfo, InteractWordV2_UserInfo_BaseInfo_OriginInfo, 2)


PB_BIND(InteractWordV2_UserInfo_MedalInfo, InteractWordV2_UserInfo_MedalInfo, 2)


PB_BIND(InteractWordV2_UserInfo_WealthInfo, InteractWordV2_UserInfo_WealthInfo, AUTO)


PB_BIND(InteractWordV2_UserInfo_GuardInfo, InteractWordV2_UserInfo_GuardInfo, AUTO)





